/**
 * بنك أهداف البرامج طويلة المدى - نسخة شاملة
 * يحتوي على أهداف_complete لبرنامجي: بورتاج (Portage) ولوفاس (LOVAAS)
 * تم تنظيم الأهداف حسب البرامج والمجالات والفئات العمرية حيث ينطبق.
 */

export const PROGRAMS = [
  { key: 'lovaas', label: 'لوفاس (ABA)', color: '#1a56db' },
  { key: 'portage', label: 'بورتاج', color: '#059669' },
  { key: 'ablls', label: 'إيبلز (ABLLS-R)', color: '#7c3aed' },
  { key: 'custom', label: 'مخصص المركز', color: '#d97706' },
];

// تم توسيع المجالات لتشمل تقسيمات دقيقة للبرامج
export const DOMAINS = [
  // مجالات عامة مشتركة
  { key: 'social', label: 'التواصل الاجتماعي والتفاعل' },
  { key: 'language', label: 'اللغة والتواصل' },
  { key: 'motor', label: 'المهارات الحركية' },
  { key: 'selfhelp', label: 'الIndependence والعناية الذاتية' },
  { key: 'cognitive', label: 'المهارات المعرفية والأكاديمية' },
  { key: 'play', label: 'مهارات اللعب' },
  { key: 'behavior', label: 'تعديل السلوك' },
  
  // مجالات خاصة ببورتاج (للرضع والنمو العام)
  { key: 'infant', label: 'نمو الرضيع (بورتاج)' },
  { key: 'preschool', label: 'ما قبل المدرسة (بورتاج)' },
  
  // مجالات خاصة بلوفاس (تقييم المهارات)
  { key: 'attention', label: 'الحضور والانتباه (لوفاس)' },
  { key: 'imitation', label: 'مهارات التقليد (لوفاس)' },
  { key: 'receptive', label: 'فهم اللغة (لوفاس)' },
  { key: 'expressive', label: 'اللغة التعبيرية (لوفاس)' },
  { key: 'abstract', label: 'اللغة المجردة (لوفاس)' },
  { key: 'preacademic', label: 'ما قبل الأكاديمي (لوفاس)' },
  { key: 'academic', label: 'المهارات الأكاديمية (لوفاس)' },
  { key: 'school_ready', label: 'الإعداد للمدرسة (لوفاس)' },
];

export function programLabel(key) { 
  return PROGRAMS.find(p => p.key === key)?.label || key; 
}

export function programColor(key) { 
  return PROGRAMS.find(p => p.key === key)?.color || '#64748b'; 
}

export function domainLabel(key) { 
  return DOMAINS.find(d => d.key === key)?.label || key; 
}

// ============================================================================
// بذور الأهداف الشاملة (SEED GOALS)
// ============================================================================
export const SEED_GOALS = [
  // ==========================================================================
  // 1. برنامج بورتاج (PORTAGE)
  // ==========================================================================
  
  // --- مجال نمو الرضيع (Infant Development) ---
  { program: 'portage', domain: 'infant', text: 'نمو بصري عام (تحت ستة أسابيع)' },
  { program: 'portage', domain: 'infant', text: 'نمو بصري عام (ستة أسابيع فأكثر)' },
  { program: 'portage', domain: 'infant', text: 'استثارة لمسية عامة (تحت ستة أسابيع)' },
  { program: 'portage', domain: 'infant', text: 'استثارة لمسية عامة (ستة أسابيع فأكثر)' },
  { program: 'portage', domain: 'infant', text: 'نمو سمعي عام (تحت ستة أسابيع)' },
  { program: 'portage', domain: 'infant', text: 'نمو سمعي عام (ستة أسابيع فأكثر)' },
  { program: 'portage', domain: 'infant', text: 'يمص' },
  { program: 'portage', domain: 'infant', text: 'يحرك رأسه للجنب عندما يكون راقداً على ظهره' },
  { program: 'portage', domain: 'infant', text: 'يفتح فمه ليستقبل زجاجة الرضاعة أو الثدي عندما تلمس الحلمة فمه' },
  { program: 'portage', domain: 'infant', text: 'يبين حساسية للتلامس الجسدي بأن يهدأ أو يبكي أو يحرك جسمه' },
  { program: 'portage', domain: 'infant', text: 'يدير رأسه تجاه الحلمة عند لمس خده' },
  { program: 'portage', domain: 'infant', text: 'ينظر في إتجاه الصوت أو يغير حركة جسمه استجابة للصوت' },
  { program: 'portage', domain: 'infant', text: 'ينظر إلى شخص يحاول أن يجذب انتباهه بالحديث أو الحركة' },
  { program: 'portage', domain: 'infant', text: 'يهدأ أو يغير حركة جسمه استجابة لوجود شخص' },
  { program: 'portage', domain: 'infant', text: 'يبدي استجابة لصوت الشخص الكبير بتحريك الجسم أو بتوقف البكاء' },
  { program: 'portage', domain: 'infant', text: 'يرفع رأسه ويبقيها مرفوعة للحظة عند حمله ورأسه مستنداً إلى الكتف' },
  { program: 'portage', domain: 'infant', text: 'يبكي بكاءً مختلفاً بإختلاف ما يضايقه' },
  { program: 'portage', domain: 'infant', text: 'ينام في الأوقات المناسبة' },
  { program: 'portage', domain: 'infant', text: 'يدفع ذراعيه عشوائياً' },
  { program: 'portage', domain: 'infant', text: 'يتتبع شيئاً بعينيه عند تحريكه ماراً بمنتصف جسمه' },
  { program: 'portage', domain: 'infant', text: 'يبتسم' },
  { program: 'portage', domain: 'infant', text: 'يتتبع الضوء بعينيه ويدير رأسه' },
  { program: 'portage', domain: 'infant', text: 'يتتبع الصوت بتحريك رأسه' },
  { program: 'portage', domain: 'infant', text: 'ينظر إلى يده' },
  { program: 'portage', domain: 'infant', text: 'يضرب بقدميه (يرفس) بقوة عندما يكون راقداً على ظهره' },
  { program: 'portage', domain: 'infant', text: 'يفتح فمه ويبدأ المص قبل أن تلمس الحلمة فمه' },
  { program: 'portage', domain: 'infant', text: 'يستمر في التواصل البصري لمدة 3 ثوان' },
  { program: 'portage', domain: 'infant', text: 'يحرك رأسه عندما يرقد على بطنه لأعلى ولأسفل وإلى الجانبين' },
  { program: 'portage', domain: 'infant', text: 'يحاول ضرب أشياء بيده' },
  { program: 'portage', domain: 'infant', text: 'يحافظ على رأسه مرفوعاً عندما يكون راقداً على بطنه لمدة 5 ثوان' },
  { program: 'portage', domain: 'infant', text: 'يتتبع الشيء على مدى 180°' },
  { program: 'portage', domain: 'infant', text: 'يبحث عن الصوت بالإلتفات برأسه في إتجاه الصوت' },
  { program: 'portage', domain: 'infant', text: 'يتحكم في رأسه وكتفيه أثناء جلوسه مستنداً إلى الوسادة' },
  { program: 'portage', domain: 'infant', text: 'ييناغي عندما يكون مسروراً' },
  { program: 'portage', domain: 'infant', text: 'يصل إلى الشيء ويحاول الإمساك به' },
  { program: 'portage', domain: 'infant', text: 'يحافظ على رأسه منتصبة وثابتة أثناء حمله رأسياً' },
  { program: 'portage', domain: 'infant', text: 'يمسك شيئاً براحة يده لمدة 30 ثانية ثم يطلقه لا إرادياً' },
  { program: 'portage', domain: 'infant', text: 'يعيد الأصوات التي يصدرها' },
  { program: 'portage', domain: 'infant', text: 'يحافظ على رأسه وصدره منتصبين أثناء رقاده على بطنه مع السند على ساعديه' },
  { program: 'portage', domain: 'infant', text: 'يفتح فمه عندما يرى ملعقة مملوءة بالطعام' },
  { program: 'portage', domain: 'infant', text: 'يضحك' },
  { program: 'portage', domain: 'infant', text: 'يبدي تمييزه لأفراد العائلة بالإبتسام أو التوقف عن البكاء' },
  { program: 'portage', domain: 'infant', text: 'يحاول التقلب باستخدام الكتفين' },
  { program: 'portage', domain: 'infant', text: 'يحرك إبهامه في مقابل الأصابع الأربعة الأخرى' },
  { program: 'portage', domain: 'infant', text: 'ييناغي (سلسلة من المقاطع)' },

  // --- مجال التنشئة الاجتماعية (Socialization) ---
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يرقب شخصاً يتحرك أمام بصره مباشرة' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يبتسم استجابة لإهتمام شخص كبير' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يصدر أصوات استجابة للاهتمام به أو الانتباه إليه' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) ينظر إلى يديه وكثيراً ما يبتسم أو يصدر أصواتاً' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يستجيب لوجوده في محيط العائلة بالابتسام أو إصدار أصوات أو بالكف عن البكاء' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يبتسم استجابة لتعبيرات وجوه الآخرين' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يبتسم ويصدر أصواتً لصورته بالمرآة' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يربت على قسمات وجه الشخص البالغ ويجذبها (الشعر، الأنف، النظارة، الخ)' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يمد ذراعه إلى شيء يقدم له' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يمد ذراعيه إلى شخص مألوف له' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يمد ذراعيه إلى صورته بالمرآة أو صورة طفل ويربت عليه' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يمسك ويتفحص شيئاً ما مقدماً له لمدة دقيقة على الأقل' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يهز أو يضغط على شيء موضوع في يده ويصدر به أصواتاً عن غير قصد' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يلعب بدون إشراف لمدة 10 دقائق' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) كثيراً ما ينشد الاتصال البصري عند الانتباه إليه لمدة 2 – 3 دقائق' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يلعب بمفرده مستمتعاً لمدة 15 – 20 دقيقة بجوار شخص كبير يمارس نشاطه' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يصدر أصواتاً ليجذب الانتباه' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يقلد لعبة "بخ" أو "عاوو"' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يصفق بيده (يصقف سوسه) مقلداً الكبار' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يلوح بيديه (باي باي) مقلداً الكبار' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يرفع ذراعيه مقلداً الكبار للتعبير عن كبير قوي' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يقدم لعبة أو شيء أو قطعة طعام لشخص كبير ولكنه لا يتخلى عنها في كل الأحيان' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يحتضن أو يربت على أو يقبل الأشخاص المألوفين' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يستجيب لنداء إسمه بالنظر أو رفع يديه رغبة في أن يحمل' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يضغط على اللعبة أو يهزها مقلداً الكبار ليحدث صوتاً' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يتناول لعبة أو شيئاً بيديه ويحرك أجزاءه' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يقدم لعبة أو شيئاً للكبير ويتركها له' },
  { program: 'portage', domain: 'social', text: '(0-1 سنة) يقلد حركات طفل آخر أثناء اللعب' },
  
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يقلد الكبير في الأعمال البسيطة (يحاول استخدام المكنسة، شد ملاية السرير...)' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يلعب بجوار طفل آخر وكل منهما يمارس أنشطة منفصلة' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يشارك في لعبة مثل دفع السيارة أو دحرجة الكرة مع طفل آخر لمدة تتراوح ما بين 2 – 5 دقائق' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يتقبل غياب والديه بالاستمرار في الأنشطة وقد يبدي احتجاجه للحظة' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يستكشف بيئته بنشاط' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يشارك مع شخص آخر في الألعاب اليدوية (يشد الحبل – ويدير المقبض)' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يحتضن ويحمل العروسة أو أي لعبة طرية' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يعطي كتاباً لشخص كبير ليقرأه له أو يشاركه تصفحه' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يجذب شخصاً آخر ليريه عملاً أو شيئاً ما' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يسحب يده قائلاً "لا..لا" عندما يقترب من شيء ممنوع مع تذكيره بذلك' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) ينتظر تلبية احتجاجاته عندما يوضع على كرسي الأطفال لإطعامه' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يلعب بجوار 2 – 3 من أقرانه' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يشارك شيئاً أو طعاماً مع طفل آخر عندما يطلب منه ذلك' },
  { program: 'portage', domain: 'social', text: '(1-2 سنة) يحيى أقرانه أو أشخاصاً مألوفين له عند تذكيره' },

  { program: 'portage', domain: 'social', text: '(2-3 سنوات) يتعاون مع طلبات الوالدين 50% من الوقت' },
  { program: 'portage', domain: 'social', text: '(2-3 سنوات) عند إعطائه التعليمات فإنه يحضر شيئاً أو شخصاً من حجرة أخرى' },
  { program: 'portage', domain: 'social', text: '(2-3 سنوات) ينصت للموسيقى أو القصص لمدة تتراوح ما بين 5 – 10 دقائق' },
  { program: 'portage', domain: 'social', text: '(2-3 سنوات) يقول (من فضلك) أو (ممكن) و(شكراً) عند تذكيره' },
  { program: 'portage', domain: 'social', text: '(2-3 سنوات) يحاول مساعدة والديه في الأعمال بالمشاركة في جزء منها' },
  { program: 'portage', domain: 'social', text: '(2-3 سنوات) يلعب لعبة ارتداء ملابس الكبار' },
  { program: 'portage', domain: 'social', text: '(2-3 سنوات) يقوم بالاختيار عندما يطلب منه ذلك' },
  { program: 'portage', domain: 'social', text: '(2-3 سنوات) يظهر تفهمه للمشاعر بالتعبير اللفظي عن الحب، الغضب، الحزن، السعادة' },

  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يغني ويقص على نغمات الموسيقى' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يتبع القواعد بتقليد أفعال الأطفال الآخرين' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يحيي الكبار المألوفين له دون تذكيره' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يتبع القواعد في الألعاب الجماعية التي يقودها شخص كبير' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يطلب الإذن لاستخدام لعبة يلعب بها أقرانه' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يقول "من فضلك" أو "ممكن" أو شكراً دون تذكيره 50% من الوقت' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يرد على المكالمات التليفونية وينادي على شخص كبير' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يأخذ دوره (ينتظر دوره)' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يتبع القواعد في الألعاب الجماعية التي يقودها طفل أكبر منه سناً' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يتعاون مع طلبات الكبار 50% من الوقت' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يبقى في المساحة المخصصة للعب بإشراف شخص كبير خارج البيت' },
  { program: 'portage', domain: 'social', text: '(3-4 سنوات) يلعب بالقرب من أطفال آخرين ويتحدث معهم أثناء قيامه بعمل معين' },

  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يطلب المساعدة عندما يواجه صعوبة' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يشارك في حديث الكبار' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يردد الأناشيد أو الأغاني أو يرقص للآخرين' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يعمل منفرداً في مهمة لمدة 20 – 30 دقيقة' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يعتذر بدون تذكيره 50% من الوقت' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يأخذ دوره مع 8 – 9 أطفال آخرين' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يلعب مع طفلين أو ثلاثة لمدة 20 دقيقة في نشاط تعاوني' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يتصرف علنية بطريقة مقبولة اجتماعياً' },
  { program: 'portage', domain: 'social', text: '(4-5 سنوات) يطلب الإذن لاستخدام أشياء تخص الآخرين 75% من الوقت' },

  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يعبر عن مشاعره الخاصة: غضب، سعادة، حب' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يلعب مع 4 – 5 أطفال في نشاط تعاوني دون إشراف دائم' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يشرح قواعد لعبة أو نشاط للآخرين' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يقلد أدوار الكبار' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يشترك في الحوار أثناء لقائه مع الأسرة' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يتبع قواعد لعبة لفظية تتطلب التفكير' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يواسي زملاء اللعب في وقت الضيق' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يختار أصدقاءه' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يخطط ويبني باستخدام أدوات بسيطة' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يحدد أهدافاً لنفسه ويقوم بالنشاط المناسب' },
  { program: 'portage', domain: 'social', text: '(5-6 سنوات) يمثل أجزاء من قصة ما ويؤدي دوراً أو يستعمل العرائس للعب' },

  // --- مجال النمو الحركي (Motor Development) ---
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يرمي بذراعيه إلى الأمام عند وضعه على بطنه لمدة 15-25 ثانية' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمسح ذراعه أمامه محمولاً على مرفقه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمسح ذراعه ويرفع رأسه 45 درجة' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يرفع رأسه إلى وضع عمودي' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يرفع رأسه 90 درجة عند وضعه على بطنه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يرفع رأسه وكتفيه وهو مستلقٍ على ظهره' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يبقى رأسه وكتفيه مرفوعان وهو مستلقٍ على ظهره 50% من الوقت' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتحرك ويزحف ويكتشف ما حوله' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتقلب من بطنه إلى جنبه ويبقى 50% من الوقت' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتدحرج إلى جنبه عند النظر إلى شيء' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتحرك بطول جسمه عند الاستلقاء' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتدحرج من جنبه إلى بطنه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتقلب من بطنه إلى ظهره' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يحاول الوصول إلى شيء وهو جالس بمساعدة شخص كبير' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يدير رأسه بحرية وهو مستلقٍ على بطنه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يحافظ على وضع الجلوس لمدة دقيقتين' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يترك الشيء الذي في يده ليمد يده إلى شيء آخر' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يقف ويقطع من مكان لآخر' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يقف منتصباً عند حافة شيء' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يرفع نفسه إلى وضع الوقوف متمسكاً بشيء أعلى وأثقل' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يزحف بطول جسمه لكي يصل إلى شيء' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يجلس وحده مستنداً' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتحول من وضع الجلوس إلى وضع الحبو مع انحناء ظهره ورأسه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) ينتقل إلى وضع الجلوس وهو مستند' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يجلس دون أن يستند' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يرمي الأشياء بشكل متعمد' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يتحرك إلى الخلف والأمام على بطنه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) ينقل شيئاً من يد إلى أخرى وهو جالس' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يحافظ على جلوسه مستنداً' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يحاول وضع نفسه على بطنه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يجلس بمفرده' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمشي ممسكاً بالأثاث أو على أطراف أصابعه' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يزحف' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمد يده وهو في وضع الجلوس' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يقف وحده لمدة دقيقة' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمشي بمساعدة' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمشي من زاوية إلى أخرى في وقت واحد' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يعرف اللعبة أو الكرة' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يضع أشياء صغيرة في وعاء' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يخفض نفسه ليجلس بعد أن كان واقفاً' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يصفق بيديه معاً' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمشي بمساحة قليلة' },
  { program: 'portage', domain: 'motor', text: '(0-1 سنة) يمشي خطوات دون أن يتكئ' },

  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يزحف إلى أعلى الدرج' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) ينتقل من وضع الجلوس إلى الوقوف' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يتحرك جالساً على لعبة ذات عجلات' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يتسلق على كرسي كبير ويجلس' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يركب لعبة ذات عجلات 4 دوائر' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يضع مكعباً في كوب' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يبني برجاً من 3 مكعبات' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يرسم علامات بقلم أو قلم تلوين' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يلعب وحده' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يمشي إلى الأمام والخلف' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يجلس على كرسي صغير' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يركع ثم يقف' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يدفع ويرمي ويلعب بالكرة' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يستعمل مقعداً أو صندوقاً صغيراً' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يصعد الدرج بمساعدة' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) ينحني من الوسط ليلتقط الأشياء دون أن يقع' },
  { program: 'portage', domain: 'motor', text: '(1-2 سنة) يركل الكرة بحركة عشوائية' },

  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يضع 4 خواتم كبيرة في عمود خلال دقيقتين' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يدير مقبض الباب' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يقفز في مكانه بقدميه معاً' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يلعب بالصلصال' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يرمي الكرة بحجم كبير' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يرمي كرة كبيرة إلى شخص كبير على بعد 1.5 متر' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يبني برجاً من 5-6 مكعبات' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يقلب صفحات الكتاب صفحة صفحة' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يفتح ويفلق لعبة صغيرة' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يطوي ورقة من نصفها بتقليد' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يركب ويلعب بالدراجة ذات العجلات الثلاث' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يخرج بنطالاً ذا أزرار' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يقفز بقدم ثابتة ومنتظمة' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يركل من شكل دائري' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يمسك القلم بين الإبهام والسبابة والوسطى' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يقفز إلى الأمام بخطوات' },
  { program: 'portage', domain: 'motor', text: '(2-3 سنوات) يقص بالقصارة ويصنع شرائح من الورق' },

  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يركب صورة من جزء لا يقل عن ثلاثة أشكال أو قطع' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يقص بالمقص' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يقفز من ارتفاع 20 سم' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يقفز بقدميه معاً إلى الأمام مسافة كبيرة' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يلعب على أطراف أصابعه' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يمشي 10 خطوات بخطوات متساوية ومتناسقة على خط مستقيم' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يتقدم 1.5 متر على عارضة ارتفاعها 30 سم' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يتراجع إلى الخلف عندما يدفعه أحد في البداية' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يمشي ويرتقي على عارضة ارتفاعها 1-2 متر' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يصعد وينزل الدرج بالتبادل بين القدمين' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يلعب كالجندى' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يرمي كرة كبيرة إليه' },
  { program: 'portage', domain: 'motor', text: '(3-4 سنوات) يقص خطاً مستقيماً طوله 12 سم دون أن ينحرف عنه أكثر من 1 سم' },

  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يقف على قدم واحدة لمدة 4-8 ثوان دون مساعدة' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يجري بمهارة' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يلعب على خشبة التوازن' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يقفز إلى الأمام 10 مرات دون أن يقع' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يقفز من ارتفاع 5 سم عن الأرض' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يضرب كرة كبيرة على الأرض ثم يلتقطها' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يشكل طيناً أو عجيناً إلى ثلاث قطع أو شكلين' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يقص على خط منحني' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يركب لعبة ذات أزرار' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يرمي الكرة ويرتقي بالقدمين بالتبادل' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يركب دراجة ذات 3 عجلات بمهارة' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يمشي على خط مستقيم بطول 5 خطوات' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يقف على قدم واحدة 5 مرات متتالية' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يرسم صورة بسيطة (مثل: بيت - شجرة - رجل)' },
  { program: 'portage', domain: 'motor', text: '(4-5 سنوات) يقص ويلصق أشكالاً بسيطة' },

  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يكتب حرفاً منفصلاً في أي مكان على الورقة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يلعب على خشبة التوازن بالمشي والأطراف والأيدي' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يتراجع على حركات رجعية بسيطة ويحافظ عليها' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يفرق أصابعه ويلعب بها' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يستعمل ورقة الكتابة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يمشي على عارضة ارتفاع 2 متر للتسلق' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يرمي بالمسطرة على هدف' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يضرب الكرة بيده نحو هدف معين' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يمشي داخل الخطوط 95% من الوقت' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يقص صورة من أكثر من جهة دون أن يبتعد عن الصورة أكثر من 1 سم' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يستعمل المبراة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يرسم أشكالاً معقدة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يركب أشكالاً بسيطة من ورقة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يثنى قطره 12 سم من ورقة مربعة بقطر 2 سم' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يمسك بكرة صغيرة أو خرزة بيد واحدة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يستطيع أن يطيح طائرة ورقية' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يضرب الكرة بالمضرب' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يرمي شيئاً من على الأرض وهو يجري' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يتزلج مسافة 2 متر' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يركب دراجة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يتسلق على الحبل' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يمشي أو يسبح على ظهره' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يرمي كرة صغيرة بيد واحدة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يمشي على قدم واحدة ثم يقفز' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يكتب اسمه على ورقة' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يقفز من ارتفاع 30 سم على قدميه معاً' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يقف على قدم واحدة لمدة 10 ثوان دون أن يتحرك' },
  { program: 'portage', domain: 'motor', text: '(5-6 سنوات) يرمي كرة على هدف ويضع جسمه على يده' },

  // --- مجال الرعاية الذاتية (Self-Help) ---
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يمص ويتناول الطعام من الأوعية' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يأكل طعاماً ممزوجاً بمفرده مثل السيريال أو البسكويت الممزوج بالحليب' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يمد يده إلى زجاجة الرضاعة' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يأكل قطع البسكويت أو الطعام الذي يعطيه له أحد الوالدين' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يمسك الزجاجة عند الرضاعة دون أي مساعدة' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يوجه الزجاجة بفمه أو يدفعها بعيداً' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يأكل طعاماً مهروساً مثل الموز أو الأفوكادو' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يشرب من كوب بمساعدة أحد الوالدين' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يأكل خبزاً أو بسكويتاً أو موزاً' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يطعم نفسه بأصابعه' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يمسك ويشرب باستخدام يديه كلتاهما' },
  { program: 'portage', domain: 'selfhelp', text: '(0-1 سنة) يأخذ لقمة بطعامه ويضعها في فمه بمساعدة' },

  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يفرد رجليه عند لبس الحذاء' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يأكل طعاماً صلباً بمفرده باستخدام الملعقة' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يمسك ويشرب من كوب بيد واحدة' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يمسح يديه بالمنشفة ثم يضعهما في الماء' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يجلس على المقعد الخاص بالأطفال أو الكرسي الصغير لمدة 5 دقائق' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يضع القبعة على رأسه ويرفعها' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يخلع الجوارب' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يدفع رجليه عبر فتحات السروال أو البنطلون' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يخلع الحذاء غير المقيد أو السائب' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يخلع معطفه الخاص عند فك الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يخلع البنطلون عند فك الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يفتح أو يغلق السحاب (الزيبر) في بعض الأحيان لكنه لا يربطه' },
  { program: 'portage', domain: 'selfhelp', text: '(1-2 سنة) يستخدم كلمات أو إشارات للإشارة إلى حاجته للذهاب إلى الحمام' },

  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يطعم نفسه باستخدام الملعقة والشوكة مع انسكاب قليل' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يأخذ منشفة من أحد الوالدين ويمسح يديه ووجهه' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يشرب سائلاً من كوب أو إبريق باستخدام مقبض' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يعرف الحذاء' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يمضغ ويبلع الأطعمة المناسبة للطفل فقط' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) ينشف يديه دون مساعدة عند إعطاء المنشفة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يطلب الذهاب للحمام حتى لو كان متسخاً' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يتحكم في عضلات الفم والبلع' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يتقلب ويلتف في البطانية ثلاث مرات عند وضعه للنوم' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يلبس الحذاء' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يفرد السروال الداخلي' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يخلع قميصاً بسيطاً مفتوحاً' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يستخدم الحمام عند الحاجة، أثناء الاستيقاظ أو بعد القيلولة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يصل إلى الماء من الصنبور دون مساعدة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) ينظم درجة حرارة الماء ويغسل يديه ووجهه عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يطلب الذهاب إلى الحمام عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يضع المعطف على علاقة ملابس بطول الطفل' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يبقى جافاً خلال القيلولة القصيرة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يتجنب الأصوات المفاجئة مثل الأبواب المغلقة أو الصفير' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يستخدم منشفة الشعر عند التذكير' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يزرر قميصاً كبيراً أو معطفاً' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يصيب هدفاً صغيراً في لعبة الرمي دون مساعدة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يغطي وجهه بمنشفة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يغسل يديه ورجليه بنفسه عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يلبس جواربه' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يلبس قميصه، حذاءه، معطفه الخاص' },
  { program: 'portage', domain: 'selfhelp', text: '(2-3 سنوات) يجد وجه المنشفة' },

  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يطعم نفسه بالكامل' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يلبس نفسه بمساعدة عند الحاجة أو لارتداء المعطف' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يمسح أنفه عند التذكير' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يستيقظ جافاً سبع ليالٍ من أصل ثمانية' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يتذكر الذهاب للحمام ويخلع ملابسه' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يلبس ويرتدي الجوارب والأحذية والملابس 75% من الوقت' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يفتح أو يغلق الأزرار الكبيرة' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) ينفخ أنفه عند التذكير' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يتجنب الأحذية المقلوبة (اليمين واليسار)' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يعلق المعطف على العلاقة ويضع الحذاء في مكانه' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يفرش أسنانه عند إعطائه تعليمات لفظية' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يلبس القفازات (بإصبع واحد لكل قفاز)' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يفتح أزراراً كبيرة على فتحات الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يزرر أزراراً كبيرة على فتحات الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: '(3-4 سنوات) يلبس الحذاء ذو الرباط' },

  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يمسح أنفه عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يتجنب المواد الخطرة والملوثة' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يغطي فمه' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يزرر قميصه' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يختار طعامه من الأطعمة التي تناولها' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يطعم نفسه بالملعقة' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يغسل يديه ووجهه' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يستخدم الأدوات الصحيحة للأكل' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يبقى جافاً طوال الليل أو يستيقظ ويذهب للحمام' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يمسح أنفه وينفخه 75% من الوقت عند الحاجة دون تذكير' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يغسل نفسه جيداً (اليدين، الوجه، الأذنين)' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يستخدم السكين لدهان قطعة من الخبز المحمص' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يربط ويغلق الحذاء أو البنطلون' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يلبس نفسه بالكامل بما في ذلك ربط الأحذية' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) ينام في سريره بينما يحمل أحد الوالدين البطانية' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يساعد في إعداد المائدة ووضع الأدوات' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يفرش أسنانه' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يذهب للحمام فيستحم ويغسل نفسه بالشامبو ويجفف نفسه ويرتدي ملابسه دون مساعدة' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يمشط شعره الطويل باستخدام المشط أو الفرشاة' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يعلق المنشفة على العلاقة' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يتصرف بحذر دون مراقبة' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يربط حذاءه بإدخال الرباط في الفتحات' },
  { program: 'portage', domain: 'selfhelp', text: '(4-5 سنوات) يربط حذاءه (عقدة)' },

  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يتحمل مسؤولية مهمة أسبوعية في المنزل عند طلب ذلك' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يختار ملابس مناسبة لدرجة الحرارة المناسبة' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يقف عند المنحدر ثم ينظر للجانبين ثم يعبر الشارع دون تذكيرات لفظية' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يضع الطعام في طبق ثم يمرر الطبق للآخرين ثم يغطي الطعام' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يحضر وجبته الخاصة من الحقيبة ويضع الزبدة أو المربى' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يتحمل مسؤولية مهمة يومية في المنزل' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) ينظم درجة حرارة الماء عند أخذ حمام ساخن أو بارد' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يحضر نفسه للنوم' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يذهب إلى المدرسة أو الملعب أو الحديقة بمفرده من المنزل' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يقطع طعامه بالسكين' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يجد الحمام العام في المكان العام' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يفتح علبة لبن مصنوعة من الكرتون' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يرمي الكرة في سلة المهملات' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يربط حبل الهاتف أو الكهرباء' },
  { program: 'portage', domain: 'selfhelp', text: '(5-6 سنوات) يربط حزام الأمان في السيارة' },

  // --- المجال المعرفي (Cognitive) ---
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يلتقط قطعة من الطعام ويضعها في فمه' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يبحث عن شيء رفعت من خط رؤيته المباشر' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يرفع شيئاً من وعاء مفتوح وذلك بوضع يده فيه' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يضع أشياء في وعاء بمقاس كبير' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يضع الأشياء في الوعاء عند الطلب اللفظي' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يضغط بيده على صندوق ليعطي صوتاً' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يضع ثلاث أدوات في وعاء' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) ينقل أداة من يد إلى أخرى لالتقاط أداة أخرى' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يسقط ويضغط على الأشياء' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يجد أداة مخفية تحت بطانية' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يدفع ثلاث مكعبات عبر خط مستقيم' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يرفع يديه عن الأشكال الهندسية' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يضع خواتم على عمود دائري عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(0-1 سنة) يقوم بحركات بسيطة عند الطلب' },

  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يفرز 6 أدوات من وعاء' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يشير إلى جزء واحد من جسمه' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يركب 3 مكعبات فوق بعضها عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يطابق أدوات متشابهة' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يفرز الأشياء' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يشير إلى نفسه عند السؤال "أين أنت؟"' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يضع 5 خواتم دائرية في عمود عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يطابق أدوات مع صور الأشياء' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يشير إلى صورة الحيوان' },
  { program: 'portage', domain: 'cognitive', text: '(1-2 سنة) يقلب من 2-3 صفحات من كتاب الصور في المرة الواحدة' },

  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يجد كتاباً معيناً عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يكمل 3 أشكال في لوحة الأشكال' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يسمي 4 صور مألوفة' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يرسم خط عمودياً بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يرسم خط أفقياً بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يرسم دائرة' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يطابق بين الألوان الأساسية' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يشير إلى كبير وصغير عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يرسم علامة (+) بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يطابق الألوان الأساسية الثلاثة' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يضع الأشياء تحت وفوق وداخل عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يسمي أدوات تصدر أصواتاً' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يضع 4 أجزاء من لعبة تركيبية معاً' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يسمي حركات تمثلها الأشياء' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يطابق الأشكال الهندسية مع صور الأشكال' },
  { program: 'portage', domain: 'cognitive', text: '(2-3 سنوات) يعد أكثر من خمسة أو ستة من المكعبات بالترتيب' },

  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يسمي الأشياء الصغيرة والكبيرة' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يشير إلى 10 أجزاء من الجسم عند التقليد للتعليمات اللفظية' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يشير إلى ولد وبنت عند الطلب اللفظي' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يخبر ما إذا كانت الأشياء ثقيلة أو خفيفة' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يضع جزأين من شكل لعمل شكل كامل' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يصف برنامجاً أو أثنين من شخصيتين من قصة أو صورة' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يلعب بدمى ويغني ويركب حركات' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يقارن 1 إلى 13 الأشياء الأكثر أو الأقل' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يشير إلى الأشياء الطويلة والقصيرة' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يخبر أي الأشياء تتناسب معاً' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يعد إلى ثلاثة بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يرتب الأشياء في فئات' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يرسم شكل V بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يرسم خط قطري من زاوية إلى الزاوية الأخرى لمربع' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يعد إلى 10 أدوات' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يبني جسراً من 3 مكعبات بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يطابق نموذجاً أو تسلسلاً من المكعبات أو الخواتم' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يرسل تسلسلاً متصلاً' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يضيف رجلاً و/أو ذراعاً إلى شكل شخص غير كامل' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يكمل صورة من 6 قطع أو أكثر بدون محاولة أو خطأ' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يسمي الأشياء إما متشابهة أو مختلفة' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يرسم مربعاً بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يسمي 3 ألوان عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(3-4 سنوات) يسمي الأشكال الهندسية: مربع، مثلث، دائرة' },

  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يطرق عدداً محدداً من الأدوات 1-5 عند الطلب اللفظي' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يسمي خمسة ألوان' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يرسم المثلث عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يذكر 4 أشياء في الصورة' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يسمي الوقت من الساعة المرتبط بنشاط' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يعيد أصوات الحيوانات المألوفة' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يخبر إذا كان الشيء أقل أو أصغر' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يخبر بما هو ناقص عندما تختفي أداة من مجموعة مكونة من 3 أدوات' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يسمي 8 ألوان' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يسمي النصف والربع' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يطابق الحروف والأرقام' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يقول لون الأشياء' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يدرس 5 صور من قصة قصيرة 3 مرات' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يرسم رجلاً (الرأس، الأطراف، الجسم)' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يعيد 5 أصوات من سلسلة' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يبني هرماً من 10 مكعبات بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يسمي طويلاً وقصيراً' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يضع أدوات بالترتيب، بالجانب، بالخلف' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يطابق مجموعات متساوية من 1 إلى 10 أشياء' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يسمي أو يشير إلى الجزء الناقص من الصورة' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يعد من الذاكرة من 1 – 20' },
  { program: 'portage', domain: 'cognitive', text: '(4-5 سنوات) يسمي الأول، الأوسط، الأخير إما موضوعاً' },

  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يعد إلى 20 ويقول الرقم والشيء' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يسمي 10 أرقام مكتوبة' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يسمي اليمين واليسار على نفسه' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يقول الحروف الأبجدية بالترتيب' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يكتب اسمه الأول' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يسمي 5 حروف كبيرة' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يرتب الأشياء للطول والعرض' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يسمي الحروف الأبجدية بالترتيب' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يضع الأرقام المكتوبة من 1 إلى 10 في الترتيب الصحيح' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يسمي وضع الأشياء إما الأول، الثاني، الثالث' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يسمي الحروف مفردة أو متصلة' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يطابق الحرف في بداية الكلمة والكلمة' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يشير إلى الأرقام المكتوبة من 1 - 25' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) ينسخ الشكل المحدد' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يكمل متاهات بسيطة' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يسمي أيام الأسبوع بالترتيب' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يستطيع أن يجمع ويوصل إلى ثلاثة مجاميع' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يقول يوماً وأسبوعاً' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يقرأ 10 كلمات بدون توجيه' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يخبر عن شيء سيساعد في موقف ما' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يشير إلى النصف والربع للأشياء' },
  { program: 'portage', domain: 'cognitive', text: '(5-6 سنوات) يعد من الذاكرة' },

  // --- المجال اللغوي (Language) ---
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يسمع الأصوات الصادرة من الآخرين' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يكرر نفس المقطع الصوتي مرتين أو ثلاث مثل (ما ما ما، با با با)' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يستجيب للإشارات بالإشارة' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) ينفذ بعض التعليمات البسيطة المصحوبة بالإشارة' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يتوقف عن النشاط 75% من الوقت عندما يقال له "لأ"' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يجيب على أسئلة بسيطة بإجابة غير لفظية' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يربط مقطعين مختلفين من خلال نداء الشخص' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يقلد أغاني الآخرين' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يستخدم كلمة واحدة بمعنى تسمية شخص أو شيء' },
  { program: 'portage', domain: 'language', text: '(0-1 سنة) يتحدث استجابة لكلام الشخص الآخر' },

  { program: 'portage', domain: 'language', text: '(1-2 سنة) يقول 5 كلمات مختلفة' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يسأل عن "المزيد"' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يقول "انتهى"' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) ينفذ تعليمات مختلفة بخطوة واحدة دون استخدام الإشارة' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يعطي أو يروي عند الطلب منه ذلك' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يشير إلى 12 شيء مألوف لديه عند ذكرها' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يشير إلى 3-5 أجزاء في صورة عند ذكرها' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يشير إلى 3 أجزاء من جسمه' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يقول اسمه الأول أو لقبه عند الطلب منه ذلك' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يجيب على سؤال "ما هذا؟" بإعطاء اسم الشيء' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يربط الكلمات والإشارات للتعبير عن رغباته المعروفة' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يسمي 5 من الحيوانات الموجودة في البيئة المحلية' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يسمي 4 أعضاء اللعبة (العائلة)' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يستخدم أصوات الحيوانات مثل الحيوانات المعروفة كالبقرة والكلب' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يسأل عن بعض أجزاء طعامه المألوف' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يسمي 3 أجزاء من جسمه أو جسم شخص آخر' },
  { program: 'portage', domain: 'language', text: '(1-2 سنة) يجيب على أسئلة "نعم" أو "لا" بإجابة مثبتة أو منفية' },

  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يربط الاسم والصفة أو الاسم والاسم في مقطع من كلمتين' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يربط الفعل والاسم في مقطع من كلمتين' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يستخدم الكلمة التي تعني الحاجة إلى الذهاب إلى الحمام' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يربط الاسم أو الفعل مع "هنا" و"هناك"' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يربط كلمتين للتعبير عن الملكية' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يستخدم "لا" في الأسئلة' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يجيب على سؤال "ماذا تفعل؟" عبر أفعاله العادية' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يجيب على أسئلة "أين"' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يسمي الأصوات المألوفة من البيئة' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يعطي أكثر من شيء عند السؤال باستخدام صيغة الجمع' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يشير إلى نفسه باستخدام الضمائر' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يشير إلى الصور المألوفة المعروفة (10 صور)' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يرفع صوت عالياً لعمره' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يخبر عن الجنس عند السؤال "أنت ولد أم بنت؟"' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) ينفذ 3 أوامر متتالية' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يستخدم الفعل المضارع بشكل صحيح' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يستخدم صيغة الجمع' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يستخدم بعض الأفعال الماضية' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يسأل أسئلة "ما هذا؟"' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يتحكم في ارتفاع الصوت 90% من الوقت' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يستخدم "هذه" و"تلك" في الحديث' },
  { program: 'portage', domain: 'language', text: '(2-3 سنوات) يستخدم كلمة "هذه" في جملة' },

  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يقول "أنا بدل أنا"' },
  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يشير إلى أشياء ليست موجودة' },
  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يجيب على أسئلة بأسماء مثل "ما اسمك؟"' },
  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يستخدم صيغة الملكية من الاسم' },
  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يستخدم "لن" في التعريف أو النفي في الحديث' },
  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يستخدم بعض الأسماء لأجزاء من الجسم' },
  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يقول "أستطيع" أو "سأفعل" قبل الفعل أو بعده' },
  { program: 'portage', domain: 'language', text: '(3-4 سنوات) يصف الأشياء مفتوحة أو مغلقة' },

  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يقول "هل" في أول السؤال عندما يكون مناسباً' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يجلس مستمعاً 5 دقائق عندما تقرأ له قصة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) ينفذ سلسلة من 3 أوامر غير متتابعة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يقول الاسم الكامل عند الطلب منه ذلك' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يجيب على أسئلة بسيطة تبدأ بـ "كيف"' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستخدم صيغة الفعل الماضي' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يخبر عن تجربة مؤلمة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يخبر عن كيفية استخدام الأشياء المعروفة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يعبر عن هذا الشيء المقبول باستخدام الضمائر' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يعيد ترتيب الكلمات بطريقة مناسبة للسؤال' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستخدم بعض صيغ الجمع الشائعة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يخبر عن حدثين بالترتيب نفسه الذي حدثا فيه' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) ينفذ 3 تعليمات' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يظهر فهم الجملة المركبة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستطيع أن يجد زوج من الصور/الأشياء عند الطلب' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستخدم "أستطيع" و"أريد" في الكلام' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستخدم جملة مرتبطة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستطيع أن يجد أشياء أعلى وأدنى عند الطلب' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستخدم النفي في "لا - لن - لن أستطيع"' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستطيع أن يشير إلى الخطوط الصغيرة في الصورة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستخدم كلمات "جيد، سيء، قليل، كثير"' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يقول الكلمة الأخيرة في النظر المعكوس' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يخبر قصة قصيرة معروفة دون استخدام صور' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يسمي الصورة التي لا تنتمي إلى فئة معينة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يخبر أن الكلمتين كانتا على نفس الوزن والاسم' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستخدم جملة مركبة' },
  { program: 'portage', domain: 'language', text: '(4-5 سنوات) يستطيع أن يخبر إذا كان الصوت عالياً أو منخفضاً' },

  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يستطيع أن يشير إلى كثير، كثير، بعض' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يخبر عن العنوان' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يقول رقم التليفون' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يستطيع أن يشير إلى أكثر، أقل، أقل' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يقول كلمة بسيطة' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يخبر عن التجارب اليومية' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يصف الموقع أو الحركة من حيث البعد والاتجاه والقرب' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يجيب على أسئلة "لماذا" بتفسير' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يضع 3-5 أجزاء متسلسلة من قصة ويرويها' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يضع الكلمات في جمل' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يستطيع أن يقول عكس' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يجيب على أسئلة "ماذا يحدث إذا..."' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يستخدم كلمة "جداً" بمعنى' },
  { program: 'portage', domain: 'language', text: '(5-6 سنوات) يسأل عن معنى كلمات جديدة أو غير مألوفة' },


  // ==========================================================================
  // 2. برنامج لوفاس (LOVAAS)
  // ==========================================================================

  // --- المجال الأول: مهارات الحضور والانتباه (Attention) ---
  { program: 'lovaas', domain: 'attention', text: 'يجلس بمفرده بطريقة مستقلة' },
  { program: 'lovaas', domain: 'attention', text: 'يتواصل ببصره استجابة لسماع اسمه' },
  { program: 'lovaas', domain: 'attention', text: 'ينظر ويتصل ببصره عند سماع أمر "أنظر إلي"' },
  { program: 'lovaas', domain: 'attention', text: 'يستجيب للأمر "ربع ايدك – ايدك على الترابيزة"' },
  { program: 'lovaas', domain: 'attention', text: 'الاستمرار في الاتصال البصري لمدة 5 ثوان استجابة لسماع اسمه' },
  { program: 'lovaas', domain: 'attention', text: 'يتصل بصرياً استجابة لسماع اسمه أثناء اللعب' },
  { program: 'lovaas', domain: 'attention', text: 'يتصل بصرياً من على مسافة' },
  { program: 'lovaas', domain: 'attention', text: 'يقول نعم عندما يناديه أحد' },
  { program: 'lovaas', domain: 'attention', text: 'يتصل ببصره خلال المحادثة' },
  { program: 'lovaas', domain: 'attention', text: 'يتصل ببصره أثناء التعليم الجماعي' },

  // --- المجال الثاني: مهارات التقليد (Imitation) ---
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: اضرب على المنضدة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: صفق بيدك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: لوح بيدك "باي"' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: ضع يدك لأعلى' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: دب برجلك على الأرض' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: اضرب بيدك على رجلك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: هز رأسك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: أومئ برأسك إلى الأمام' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: لف بجسمك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: غطي وجهك بيديك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: اضرب على أكتافك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: اقفز' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: ربع يديك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: اضرب على بطنك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: اقرع الباب' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: ضع يديك على وسطك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: اضرب على رأسك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الجسم الكبرى: ادعك يديك ببعضها' },
  
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: ضع المكعب في العلبة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: رن الجرس' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: ادفع العربة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: لوح بالعلم' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: اضرب على طبلة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: البس القبعة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: شخبط' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: جفف فمك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: اضرب بلعبة الشاكوش' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: هز الشخشيخة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: اطعم العروسة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: ضع التليفون على أذنك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: اشرب من الكوب' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: انفخ في الزمارة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: سرح شعرك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: دحرج اللعبة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: ضع العملة في الحصالة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: قبل العروسة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات باستعمال الأشياء: الصق الورقة' },

  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: شبك يديك ببعضها' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: افتح واغلق يديك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: انقر "اضرب" اصبعي السبابة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: انقر "اضرب" اصبعي الإبهام' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: طرقع أصابعك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: اضرب اصبع السبابة بالإبهام' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: أشر إلى أجزاء جسمك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: أشر بإصبع السبابة إلى باطن اليد' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: مد إصبع السبابة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: ضع إصبع الإبهام لأعلى' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد الحركات الدقيقة: قم بعمل علامة السلام' },

  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: فتح الفم' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: العق باللسان خارجاً' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: ضم الشفتان' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: اخبط أسنانك ببعضها' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: انفخ' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: ابتسم' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: كشر' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: قبل' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: ارفع لسانك لأعلى' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات الفم والشفاة: ضع أسنانك العليا على الشفاة السفلى' },

  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: اقفز لأعلى ولأسفل' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: لف' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: افرد ذراعيك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: امشي' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: اجلس على الأرض' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: اضرب بيديك على الأرض' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: اطرق الباب' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: ازحف' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: امشي حول الكرسي' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: استلقي على الأرض' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: ضع يديك على فخذيك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: المس بأطراف أصابعك قدميك' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: اجري ثم قف' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: ارفع قدم واحدة لأعلى' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: نط / احجل' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: قلد حركة طيران الطائرة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: ازحف تحت المنضدة' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: ارفع الكرسي لأعلى' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى من وضع الوقوف: شوط الكرة' },

  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى متسلسلة (نشاطين معاً)' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات كبرى متسلسلة بالأشياء' },
  
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات مقترنة بأصوات: ادفع العربة وقل بيب بيب' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات مقترنة بأصوات: ضع سماعة التليفون على أذنك وقل ألو' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات مقترنة بأصوات: اضرب على مفاتيح البيانو وقل لا لا لا' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد حركات مقترنة بأصوات: تظاهر بأنك تأكل ساندويتش لعبة ثم قل هم هم' },
  
  { program: 'lovaas', domain: 'imitation', text: 'يقلد نماذج بالمكعبات' },
  { program: 'lovaas', domain: 'imitation', text: 'ينسخ رسوماً بسيطة (خطوط - حروف - أرقام - أشكال هندسية)' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد تتابع معقد' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد لعب قرينه' },
  { program: 'lovaas', domain: 'imitation', text: 'يقلد استجابات قرينه اللفظية' },

  // --- المجال الثالث: مهارات فهم اللغة (Receptive Language) ---
  { program: 'lovaas', domain: 'receptive', text: 'يتبع تعليمات من خطوة واحدة' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على أجزاء الجسم' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الأشياء' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الصور' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الأشخاص المألوفين' },
  { program: 'lovaas', domain: 'receptive', text: 'يتبع أوامر الفعل' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الأفعال في الصور' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الأشياء في البيئة' },
  { program: 'lovaas', domain: 'receptive', text: 'يشير إلى صورة في كتاب' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على استعمالات الأشياء' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الملكية' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الأصوات في البيئة' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على حجرات المنزل' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على المشاعر والانفعالات' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الأماكن' },
  { program: 'lovaas', domain: 'receptive', text: 'يتبع تعليمات من خطوتين' },
  { program: 'lovaas', domain: 'receptive', text: 'يعطي شيئين' },
  { program: 'lovaas', domain: 'receptive', text: 'يستعيد أشياء لا يراها' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الصفات المميزة للأشياء' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على المساعدين في المجتمع "المهن"' },
  { program: 'lovaas', domain: 'receptive', text: 'يتظاهر بعمل أشياء' },
  { program: 'lovaas', domain: 'receptive', text: 'يعرف فئات الأشياء' },
  { program: 'lovaas', domain: 'receptive', text: 'يعرف الضمائر' },
  { program: 'lovaas', domain: 'receptive', text: 'يتبع التعليمات التي تحتوي على حروف الجر' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الأشياء عندما توصف له في مجال بصره' },
  { program: 'lovaas', domain: 'receptive', text: 'يضع الكروت المتسلسلة بالترتيب' },
  { program: 'lovaas', domain: 'receptive', text: 'يعرف المذكر والمؤنث' },
  { program: 'lovaas', domain: 'receptive', text: 'يعرف العناصر الناقصة' },
  { program: 'lovaas', domain: 'receptive', text: 'يجيب على الأسئلة عن الأشياء والصور' },
  { program: 'lovaas', domain: 'receptive', text: 'يجيب بنعم أو لا استجابة للأسئلة عن الأشياء والنشاطات' },
  { program: 'lovaas', domain: 'receptive', text: 'يسمي الأشياء باللمس' },
  { program: 'lovaas', domain: 'receptive', text: 'يتبع تعليمات ذات 3 خطوات' },
  { program: 'lovaas', domain: 'receptive', text: 'يتبع تعليمات معقدة من على بعد' },
  { program: 'lovaas', domain: 'receptive', text: 'يسمي شخص / مكان / شئ عندما يوصف له' },
  { program: 'lovaas', domain: 'receptive', text: 'يحدد اسم شئ عندما يظهر له جزء واحد منه' },
  { program: 'lovaas', domain: 'receptive', text: 'يعرف العناصر المتشابهة' },
  { program: 'lovaas', domain: 'receptive', text: 'يعرف العناصر المختلفة' },
  { program: 'lovaas', domain: 'receptive', text: 'يتعرف على الشئ المختلف في صفاته عن مجموعته' },
  { program: 'lovaas', domain: 'receptive', text: 'يعرف المفرد والجمع' },
  { program: 'lovaas', domain: 'receptive', text: 'يجيب عن أسئلة "ماذا / أين / كيف / من" عن قصة قصيرة' },
  { program: 'lovaas', domain: 'receptive', text: 'يجيب عن أسئلة "ماذا / أين / كيف / من" عن موضوع' },
  { program: 'lovaas', domain: 'receptive', text: 'يتبع التعليمات "اسأل - أخبر"' },
  { program: 'lovaas', domain: 'receptive', text: 'يجد شئ مختبئ أعطي له دلائل عن مكانه' },
  { program: 'lovaas', domain: 'receptive', text: 'يميز بين إلقاء السؤال وتبادل المعلومة' },

  // --- المجال الرابع: مهارات اللغة التعبيرية (Expressive Language) ---
  { program: 'lovaas', domain: 'expressive', text: 'يشير إلى الأشياء التي يرغبها عند سؤاله عما يريد' },
  { program: 'lovaas', domain: 'expressive', text: 'يشير بإصبعه تلقائياً إلى ما يريد' },
  { program: 'lovaas', domain: 'expressive', text: 'يقلد الأصوات والكلمات' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الأشياء' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الصور' },
  { program: 'lovaas', domain: 'expressive', text: 'يطلب رغباته شفاهة' },
  { program: 'lovaas', domain: 'expressive', text: 'يعبر حركياً بـ "نعم / لا"' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الأشخاص المألوفين' },
  { program: 'lovaas', domain: 'expressive', text: 'يقوم بالاختيار' },
  { program: 'lovaas', domain: 'expressive', text: 'يتبادل التهاني' },
  { program: 'lovaas', domain: 'expressive', text: 'يجيب على الأسئلة الاجتماعية' },
  { program: 'lovaas', domain: 'expressive', text: 'يحدد الأفعال "في الصور / على الآخرين / على نفسه"' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الأشياء باستعمالاتها' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الملكية' },
  { program: 'lovaas', domain: 'expressive', text: 'يقلد جمل من كلمتين أو ثلاث' },
  { program: 'lovaas', domain: 'expressive', text: 'يطلب ما يريد في جملة استجابة لسؤاله "ماذا تريد؟"' },
  { program: 'lovaas', domain: 'expressive', text: 'يطلب ما يريد تلقائياً في جملة' },
  { program: 'lovaas', domain: 'expressive', text: 'ينادي والديه عن بعد' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي شيئاً معتمداً على وظيفته' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي "يحدد" وظيفة الأشياء' },
  { program: 'lovaas', domain: 'expressive', text: 'يحدد ويشير إلى أجزاء جسمه تبعا لوظيفتها' },
  { program: 'lovaas', domain: 'expressive', text: 'يذكر وظيفة أجزاء الجسم' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الأماكن' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الانفعالات' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي مجموعات من الأشياء' },
  { program: 'lovaas', domain: 'expressive', text: 'يذكر جمل بسيطة' },
  { program: 'lovaas', domain: 'expressive', text: 'يتبادل معلومة "الاسم / العمر / ..... إلخ"' },
  { program: 'lovaas', domain: 'expressive', text: 'يقول لا أعرف عندما يسأل عن شئ لا يعرفه' },
  { program: 'lovaas', domain: 'expressive', text: 'يسأل أسئلة "ما هذا – أين يوجد؟"' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي حروف الجر' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الضمائر' },
  { program: 'lovaas', domain: 'expressive', text: 'يجيب على أسئلة معلومات عامة' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي النوع "ذكر / أنثى"' },
  { program: 'lovaas', domain: 'expressive', text: 'يصف الصور في جملة' },
  { program: 'lovaas', domain: 'expressive', text: 'يصف الأشياء التي يراها وأهم صفاتها' },
  { program: 'lovaas', domain: 'expressive', text: 'يستطيع استدعاء خبرات سابقة حديثة' },
  { program: 'lovaas', domain: 'expressive', text: 'يجيب على الأسئلة التي تبدأ بـ "أين؟"' },
  { program: 'lovaas', domain: 'expressive', text: 'يسمي الموجودات في الحجرة' },
  { program: 'lovaas', domain: 'expressive', text: 'يذكر وظائف الحجرات' },
  { program: 'lovaas', domain: 'expressive', text: 'يذكر وظائف المساعدين في المجتمع' },
  { program: 'lovaas', domain: 'expressive', text: 'يجيب على الأسئلة التي تبدأ بـ "متى؟"' },
  { program: 'lovaas', domain: 'expressive', text: 'يصف تسلسل الصور' },
  { program: 'lovaas', domain: 'expressive', text: 'يوصل رسالة صغيرة' },
  { program: 'lovaas', domain: 'expressive', text: 'يلعب أدوار بالدمى' },
  { program: 'lovaas', domain: 'expressive', text: 'يعرض المساعدة' },
  { program: 'lovaas', domain: 'expressive', text: 'يقول لا أعرف للسؤال غير المألوف' },
  { program: 'lovaas', domain: 'expressive', text: 'يحدد المجموعة التي ينتمي إليها الشئ' },
  { program: 'lovaas', domain: 'expressive', text: 'يحدد العناصر في مجموعات' },
  { program: 'lovaas', domain: 'expressive', text: 'يعيد قص حكاية' },
  { program: 'lovaas', domain: 'expressive', text: 'يصف أشياء لا يراها بخصائصها' },
  { program: 'lovaas', domain: 'expressive', text: 'يستدعي أحداث ماضية' },
  { program: 'lovaas', domain: 'expressive', text: 'يصف مواضيع' },
  { program: 'lovaas', domain: 'expressive', text: 'يحكي قصة' },
  { program: 'lovaas', domain: 'expressive', text: 'يعبر عن الخلط "التشويش" ويسأل لكي تتضح الصورة' },
  { program: 'lovaas', domain: 'expressive', text: 'يحدد ضمائر الملكية المتقدمة' },
  { program: 'lovaas', domain: 'expressive', text: 'يستخدم زمن الفعل الصحيح' },
  { program: 'lovaas', domain: 'expressive', text: 'يسأل سؤال ويخبر عن معلومة' },
  { program: 'lovaas', domain: 'expressive', text: 'يستمع لحديث ويجيب أسئلة عن المحادثة' },
  { program: 'lovaas', domain: 'expressive', text: 'يطلب المعرفة' },
  { program: 'lovaas', domain: 'expressive', text: 'يجيب على أسئلة معلومات عامة متقدمة' },
  { program: 'lovaas', domain: 'expressive', text: 'يصف كيف يفعل شئ ما' },
  { program: 'lovaas', domain: 'expressive', text: 'يصف التشابه والتضاد بين الأشياء' },
  { program: 'lovaas', domain: 'expressive', text: 'يسأل أسئلة عن "أيا من؟"' },
  { program: 'lovaas', domain: 'expressive', text: 'يسأل بـ "ماذا/كيف/أين/من" عندما نمده بمعلومة غامضة' },

  // --- المجال الخامس: مهارات اللغة المجردة (Abstract Language) ---
  { program: 'lovaas', domain: 'abstract', text: 'يجيب عن أسئلة "لماذا؟"' },
  { program: 'lovaas', domain: 'abstract', text: 'يجيب عن أسئلة "إذا كان؟"' },
  { program: 'lovaas', domain: 'abstract', text: 'يصنع تكملة منطقية للجمل' },
  { program: 'lovaas', domain: 'abstract', text: 'يصف الشواذ "الغرائب" في الصور' },
  { program: 'lovaas', domain: 'abstract', text: 'يجيب بنعم أو لا عن معلومات حقيقية' },
  { program: 'lovaas', domain: 'abstract', text: 'يتنبأ بالنتائج' },
  { program: 'lovaas', domain: 'abstract', text: 'يأخذ أفكار أخرى' },
  { program: 'lovaas', domain: 'abstract', text: 'يقدم توضيح "تفسير"' },
  { program: 'lovaas', domain: 'abstract', text: 'يستبعد عناصر معتمداً على خصائصها ومجموعاتها' },
  { program: 'lovaas', domain: 'abstract', text: 'يعرف الموضوع الرئيسي في قصة ومحادثة' },

  // --- المجال السادس: مهارات ما قبل الأكاديمي (Pre-Academic) ---
  { program: 'lovaas', domain: 'preacademic', text: 'يستطيع المطابقة بين الأشياء المتماثلة' },
  { program: 'lovaas', domain: 'preacademic', text: 'يستطيع المطابقة بين الصور المتماثلة' },
  { program: 'lovaas', domain: 'preacademic', text: 'يستطيع المطابقة بين الأشياء وصورها' },
  { program: 'lovaas', domain: 'preacademic', text: 'يستطيع المطابقة بين الألوان والأشكال والحروف والأرقام' },
  { program: 'lovaas', domain: 'preacademic', text: 'يربط بين الأشياء غير المتماثلة "المعكوسات"' },
  { program: 'lovaas', domain: 'preacademic', text: 'يربط بين الأشياء في مجموعاتها "العلاقات"' },
  { program: 'lovaas', domain: 'preacademic', text: 'يتعرف على الألوان' },
  { program: 'lovaas', domain: 'preacademic', text: 'يتعرف على الأشكال' },
  { program: 'lovaas', domain: 'preacademic', text: 'يتعرف على الحروف' },
  { program: 'lovaas', domain: 'preacademic', text: 'يتعرف على الأرقام' },
  { program: 'lovaas', domain: 'preacademic', text: 'يردد الأرقام حتى 10' },
  { program: 'lovaas', domain: 'preacademic', text: 'يعد الأشياء' },
  { program: 'lovaas', domain: 'preacademic', text: 'يصل بين العناصر من نفس الفئة' },
  { program: 'lovaas', domain: 'preacademic', text: 'يعطي كمية محددة من الأشياء' },
  { program: 'lovaas', domain: 'preacademic', text: 'يصل بين الأرقام والكميات' },
  { program: 'lovaas', domain: 'preacademic', text: 'يصل بين الأشكال المختلفة للحروف أول الكلام وآخره' },
  { program: 'lovaas', domain: 'preacademic', text: 'يصل بين الكلمات المتطابقة' },
  { program: 'lovaas', domain: 'preacademic', text: 'يتعرف على الأكثر والأقل' },
  { program: 'lovaas', domain: 'preacademic', text: 'يسلسل الأرقام والحروف' },
  { program: 'lovaas', domain: 'preacademic', text: 'يستكمل واجبات منزلية بسيطة' },
  { program: 'lovaas', domain: 'preacademic', text: 'ينسخ الأرقام والحروف' },
  { program: 'lovaas', domain: 'preacademic', text: 'يتعرف على الأرقام المكتوبة' },
  { program: 'lovaas', domain: 'preacademic', text: 'يرسم لوحات بسيطة' },
  { program: 'lovaas', domain: 'preacademic', text: 'يكتب اسمه' },
  { program: 'lovaas', domain: 'preacademic', text: 'يلصق ويعجن' },
  { program: 'lovaas', domain: 'preacademic', text: 'يقص بالمقص' },
  { program: 'lovaas', domain: 'preacademic', text: 'يلون داخل حدود مرسومة' },

  // --- المجال السابع: المهارات الأكاديمية (Academic) ---
  { program: 'lovaas', domain: 'academic', text: 'يعرف أشخاص / أماكن / أشياء' },
  { program: 'lovaas', domain: 'academic', text: 'يكمل نموذج' },
  { program: 'lovaas', domain: 'academic', text: 'يطابق كلمات مكتوبة بأشياء وأشياء بكلمات مكتوبة' },
  { program: 'lovaas', domain: 'academic', text: 'يقرأ كلمات شائعة' },
  { program: 'lovaas', domain: 'academic', text: 'يحدد هجاء "أصوات الحروف"' },
  { program: 'lovaas', domain: 'academic', text: 'يذكر كلمة تبدأ بصوت حرف' },
  { program: 'lovaas', domain: 'academic', text: 'يسمي حروف في أول الكلام وأوسطه وآخره' },
  { program: 'lovaas', domain: 'academic', text: 'يستهجأ كلمات بسيطة' },
  { program: 'lovaas', domain: 'academic', text: 'يذكر معنى كلمة' },
  { program: 'lovaas', domain: 'academic', text: 'يذكر مترادفات بسيطة' },
  { program: 'lovaas', domain: 'academic', text: 'يذكر علاقات زمنية' },
  { program: 'lovaas', domain: 'academic', text: 'يذكر الترتيب الأول، الثاني، الثالث ...... إلخ' },
  { program: 'lovaas', domain: 'academic', text: 'يذكر كلمات مسجوعة' },
  { program: 'lovaas', domain: 'academic', text: 'يكتب كلمات بسيطة من الذاكرة' },
  { program: 'lovaas', domain: 'academic', text: 'يضيف أعداد أحادية "تحت العشرة"' },

  // --- المجال الثامن: مهارات الإعداد للمدرسة (School Readiness) ---
  { program: 'lovaas', domain: 'school_ready', text: 'ينتظر الدور' },
  { program: 'lovaas', domain: 'school_ready', text: 'يظهر استجابات جديدة خلال الملاحظة' },
  { program: 'lovaas', domain: 'school_ready', text: 'يتبع التعليمات في المجموعة' },
  { program: 'lovaas', domain: 'school_ready', text: 'يتبادل العبارات "المعلومات" الاجتماعية في الجماعة' },
  { program: 'lovaas', domain: 'school_ready', text: 'يغني أغاني الأطفال داخل الشرفة' },
  { program: 'lovaas', domain: 'school_ready', text: 'يجيب عندما يناديه "يستدعيه" أحد' },
  { program: 'lovaas', domain: 'school_ready', text: 'يرفع يده ليجيب عن سؤال' },
  { program: 'lovaas', domain: 'school_ready', text: 'يستمع إلى قصة ويجيب عن أسئلة عليها' },
  { program: 'lovaas', domain: 'school_ready', text: 'يمثل ويحكي' },

  // --- المجال التاسع: مهارات رعاية الذات (Self-Care) ---
  { program: 'lovaas', domain: 'selfhelp', text: 'يشرب من الكوب' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يستعمل الملعقة أو الشوكة عند الطعام' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يخلع الحذاء' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يخلع الشراب' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يخلع البنطلون' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يخلع القميص أو التي شيرت' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يستخدم الفوطة أو المناديل الورقية' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يتدرب على التحكم في التبول' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يلبس البنطلون' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يلبس القميص' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يلبس البلوفر' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يلبس الحذاء' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يلبس الشراب' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يغسل يديه' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يتدرب على التحكم في التبرز' },
  { program: 'lovaas', domain: 'selfhelp', text: 'المبادرة على طلب الاستحمام' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يغسل أسنانه' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يغلق ويفتح السوستة' },
  { program: 'lovaas', domain: 'selfhelp', text: 'يزرر الزراير' },
];
