/**
 * بنك أهداف البرامج طويلة المدى
 * تم تحديثه بأهداف حقيقية من برنامج بورتاج (Portage)
 */

export const PROGRAMS = [
  { key: 'lovaas', label: 'لوفاس (ABA)', color: '#1a56db' },
  { key: 'portage', label: 'بورتاج', color: '#059669' },
  { key: 'ablls', label: 'إيبلز (ABLLS-R)', color: '#7c3aed' },
  { key: 'custom', label: 'مخصص المركز', color: '#d97706' },
];

export const DOMAINS = [
  { key: 'infant', label: 'نمو الرضيع (بورتاج)' },
  { key: 'social', label: 'التنشئة الاجتماعية' },
  { key: 'language', label: 'اللغة والتواصل' },
  { key: 'motor', label: 'المهارات الحركية' },
  { key: 'selfhelp', label: 'الرعاية الذاتية' },
  { key: 'cognitive', label: 'المهارات المعرفية' },
  { key: 'play', label: 'مهارات اللعب' },
  { key: 'behavior', label: 'تعديل السلوك' },
];

export function programLabel(key) { return PROGRAMS.find(p => p.key === key)?.label || key; }
export function programColor(key) { return PROGRAMS.find(p => p.key === key)?.color || '#64748b'; }
export function domainLabel(key) { return DOMAINS.find(d => d.key === key)?.label || key; }

// بذور أولية - أهداف برنامج بورتاج الحقيقية
export const SEED_GOALS = [
  // ==========================================
  // 1. مجال نمو الرضيع (Portage Infant)
  // ==========================================
  { program: 'portage', domain: 'infant', text: 'نمو بصري عام (تحت ستة أسابيع)' },
  { program: 'portage', domain: 'infant', text: 'نمو بصري عام (ستة أسابيع فأكثر)' },
  { program: 'portage', domain: 'infant', text: 'استثارة لمسية عامة (تحت ستة أسابيع)' },
  { program: 'portage', domain: 'infant', text: 'استثارة لمسية عامة (ستة أسابيع فأكثر)' },
  { program: 'portage', domain: 'infant', text: 'نمو سمعي عام (تحت ستة أسابيع)' },
  { program: 'portage', domain: 'infant', text: 'نمو سمعي عام (ستة أسابيع فأكثر)' },
  { program: 'portage', domain: 'infant', text: 'يمص' },
  { program: 'portage', domain: 'infant', text: 'يحرك رأسه للجنب عندما يكون راقداً على ظهره' },
  { program: 'portage', domain: 'infant', text: 'يفتح فمه ليستقبل زجاجة الرضاعة أو الثدي عندما تلمس الحلمة فمه' },
  { program: 'portage', domain: 'infant', text: 'يبين حساسية للتلامس الجسدي بأن يهدأ أو يبكي أو يحرك جسمه' },
  { program: 'portage', domain: 'infant', text: 'يدير رأسه تجاه الحلمة عند لمس خده' },
  { program: 'portage', domain: 'infant', text: 'ينظر في إتجاه الصوت أو يغير حركة جسمه استجابة للصوت' },
  { program: 'portage', domain: 'infant', text: 'ينظر إلى شخص يحاول أن يجذب انتباهه بالحديث أو الحركة' },
  { program: 'portage', domain: 'infant', text: 'يهدأ أو يغير حركة جسمه استجابة لوجود شخص' },
  { program: 'portage', domain: 'infant', text: 'يبدي استجابة لصوت الشخص الكبير بتحريك الجسم أو بتوقف البكاء' },
  { program: 'portage', domain: 'infant', text: 'يرفع رأسه ويبقيها مرفوعة للحظة عند حمله ورأسه مستنداً إلى الكتف' },
  { program: 'portage', domain: 'infant', text: 'يبكي بكاءً مختلفاً بإختلاف ما يضايقه' },
  { program: 'portage', domain: 'infant', text: 'ينام في الأوقات المناسبة' },
  { program: 'portage', domain: 'infant', text: 'يدفع ذراعيه عشوائياً' },
  { program: 'portage', domain: 'infant', text: 'يتتبع شيئاً بعينيه عند تحريكه ماراً بمنتصف جسمه' },
  { program: 'portage', domain: 'infant', text: 'يبتسم' },
  { program: 'portage', domain: 'infant', text: 'يتتبع الضوء بعينيه ويدير رأسه' },
  { program: 'portage', domain: 'infant', text: 'يتتبع الصوت بتحريك رأسه' },
  { program: 'portage', domain: 'infant', text: 'ينظر إلى يده' },
  { program: 'portage', domain: 'infant', text: 'يضرب بقدميه (يرفس) بقوة عندما يكون راقداً على ظهره' },
  { program: 'portage', domain: 'infant', text: 'يفتح فمه ويبدأ المص قبل أن تلمس الحلمة فمه' },
  { program: 'portage', domain: 'infant', text: 'يستمر في التواصل البصري لمدة 3 ثوان' },
  { program: 'portage', domain: 'infant', text: 'يحرك رأسه عندما يرقد على بطنه لأعلى ولأسفل وإلى الجانبين' },
  { program: 'portage', domain: 'infant', text: 'يحاول ضرب أشياء بيده' },
  { program: 'portage', domain: 'infant', text: 'يحتفظ برأسه مرفوعاً عندما يكون راقداً على بطنه لمدة 5 ثوان' },
  { program: 'portage', domain: 'infant', text: 'يتتبع الشيء على مدى 180°' },
  { program: 'portage', domain: 'infant', text: 'يبحث عن الصوت بالإلتفات برأسه في إتجاه الصوت' },
  { program: 'portage', domain: 'infant', text: 'يتحكم في رأسه وكتفيه أثناء جلوسه مستنداً إلى الوسادة' },
  { program: 'portage', domain: 'infant', text: 'ييناغي عندما يكون مسروراً' },
  { program: 'portage', domain: 'infant', text: 'يصل إلى الشيء ويحاول الإمساك به' },
  { program: 'portage', domain: 'infant', text: 'يحافظ على رأسه منتصبة وثابتة أثناء حمله رأسياً' },
  { program: 'portage', domain: 'infant', text: 'يمسك شيئاً براحة يده لمدة 30 ثانية ثم يطلقه لا إرادياً' },
  { program: 'portage', domain: 'infant', text: 'يعيد الأصوات التي يصدرها' },
  { program: 'portage', domain: 'infant', text: 'يحافظ على رأسه وصدره منتصبين أثناء رقاده على بطنه مع السند على ساعديه' },
  { program: 'portage', domain: 'infant', text: 'يفتح فمه عندما يرى ملعقة مملوءة بالطعام' },
  { program: 'portage', domain: 'infant', text: 'يضحك' },
  { program: 'portage', domain: 'infant', text: 'يبدي تمييزه لأفراد العائلة بالإبتسام أو التوقف عن البكاء' },
  { program: 'portage', domain: 'infant', text: 'يحاول التقلب باستخدام الكتفين' },
  { program: 'portage', domain: 'infant', text: 'يحرك إبهامه في مقابل الأصابع الأربعة الأخرى' },
  { program: 'portage', domain: 'infant', text: 'ييناغي (سلسلة من المقاطع)' },

  // ==========================================
  // 2. مجال التنشئة الاجتماعية (Portage Social)
  // ==========================================
  // 0-1 سنة
  { program: 'portage', domain: 'social', text: 'يرقب شخصاً يتحرك أمام بصره مباشرة' },
  { program: 'portage', domain: 'social', text: 'يبتسم استجابة لإهتمام شخص كبير' },
  { program: 'portage', domain: 'social', text: 'يصدر أصوات استجابة للاهتمام به أو الانتباه إليه' },
  { program: 'portage', domain: 'social', text: 'ينظر إلى يديه وكثيراً ما يبتسم أو يصدر أصواتاً' },
  { program: 'portage', domain: 'social', text: 'يستجيب لوجوده في محيط العائلة بالابتسام أو إصدار أصوات أو بالكف عن البكاء' },
  { program: 'portage', domain: 'social', text: 'يبتسم استجابة لتعبيرات وجوه الآخرين' },
  { program: 'portage', domain: 'social', text: 'يبتسم ويصدر أصواتً لصورته بالمرآة' },
  { program: 'portage', domain: 'social', text: 'يربت على قسمات وجه الشخص البالغ ويجذبها (الشعر، الأنف، النظارة، الخ)' },
  { program: 'portage', domain: 'social', text: 'يمد ذراعه إلى شيء يقدم له' },
  { program: 'portage', domain: 'social', text: 'يمد ذراعيه إلى شخص مألوف له' },
  { program: 'portage', domain: 'social', text: 'يمد ذراعيه إلى صورته بالمرآة أو صورة طفل ويربت عليه' },
  { program: 'portage', domain: 'social', text: 'يمسك ويتفحص شيئاً ما مقدماً له لمدة دقيقة على الأقل' },
  { program: 'portage', domain: 'social', text: 'يهز أو يضغط على شيء موضوع في يده ويصدر به أصواتاً عن غير قصد' },
  { program: 'portage', domain: 'social', text: 'يلعب بدون إشراف لمدة 10 دقائق' },
  { program: 'portage', domain: 'social', text: 'كثيراً ما ينشد الاتصال البصري عند الانتباه إليه لمدة 2 – 3 دقائق' },
  { program: 'portage', domain: 'social', text: 'يلعب بمفرده مستمتعاً لمدة 15 – 20 دقيقة بجوار شخص كبير يمارس نشاطه' },
  { program: 'portage', domain: 'social', text: 'يصدر أصواتاً ليجذب الانتباه' },
  { program: 'portage', domain: 'social', text: 'يقلد لعبة "بخ" أو "عاوو"' },
  { program: 'portage', domain: 'social', text: 'يصفق بيده (يصقف سوسه) مقلداً الكبار' },
  { program: 'portage', domain: 'social', text: 'يلوح بيديه (باي باي) مقلداً الكبار' },
  { program: 'portage', domain: 'social', text: 'يرفع ذراعيه مقلداً الكبار للتعبير عن كبير قوي (أد كده) بالتعبير الحركي' },
  { program: 'portage', domain: 'social', text: 'يقدم لعبة أو شيء أو قطعة طعام لشخص كبير ولكنه لا يتخلى عنها في كل الأحيان' },
  { program: 'portage', domain: 'social', text: 'يحتضن أو يربت على أو يقبل الأشخاص المألوفين' },
  { program: 'portage', domain: 'social', text: 'يستجيب لنداء إسمه بالنظر أو رفع يديه رغبة في أن يحمل' },
  { program: 'portage', domain: 'social', text: 'يضغط على اللعبة أو يهزها مقلداً الكبار ليحدث صوتاً' },
  { program: 'portage', domain: 'social', text: 'يتناول لعبة أو شيئاً بيديه ويحرك أجزاءه' },
  { program: 'portage', domain: 'social', text: 'يقدم لعبة أو شيئاً للكبير ويتركها له' },
  { program: 'portage', domain: 'social', text: 'يقلد حركات طفل آخر أثناء اللعب' },
  // 1-2 سنة
  { program: 'portage', domain: 'social', text: 'يقلد الكبير في الأعمال البسيطة (يحاول استخدام المكنسة، شد ملاية السرير، يضع الملابس في السلة)' },
  { program: 'portage', domain: 'social', text: 'يلعب بجوار طفل آخر وكل منهما يمارس أنشطة منفصلة' },
  { program: 'portage', domain: 'social', text: 'يشارك في لعبة مثل دفع السيارة أو دحرجة الكرة مع طفل آخر لمدة تتراوح ما بين 2 – 5 دقائق' },
  { program: 'portage', domain: 'social', text: 'يتقبل غياب والديه بالاستمرار في الأنشطة وقد يبدي احتجاجه للحظة' },
  { program: 'portage', domain: 'social', text: 'يستكشف بيئته بنشاط' },
  { program: 'portage', domain: 'social', text: 'يشارك مع شخص آخر في الألعاب اليدوية (يشد الحبل – ويدير المقبض)' },
  { program: 'portage', domain: 'social', text: 'يحتضن ويحمل العروسة أو أي لعبة طرية' },
  { program: 'portage', domain: 'social', text: 'يعطي كتاباً لشخص كبير ليقرأه له أو يشاركه تصفحه' },
  { program: 'portage', domain: 'social', text: 'يجذب شخصاً آخر ليريه عملاً أو شيئاً ما' },
  { program: 'portage', domain: 'social', text: 'يسحب يده قائلاً "لا..لا" عندما يقترب من شيء ممنوع مع تذكيره بذلك' },
  { program: 'portage', domain: 'social', text: 'ينتظر تلبية احتجاجاته عندما يوضع على كرسي الأطفال لإطعامه أو الطاولة لتغيير ملابسه' },
  { program: 'portage', domain: 'social', text: 'يلعب بجوار 2 – 3 من أقرانه' },
  { program: 'portage', domain: 'social', text: 'يشارك شيئاً أو طعاماً مع طفل آخر عندما يطلب منه ذلك' },
  { program: 'portage', domain: 'social', text: 'يحيى أقرانه أو أشخاصاً مألوفين له عند تذكيره' },
  // 2-3 سنوات
  { program: 'portage', domain: 'social', text: 'يتعاون مع طلبات الوالدين 50% من الوقت' },
  { program: 'portage', domain: 'social', text: 'عند إعطائه التعليمات فإنه يحضر شيئاً أو شخصاً من حجرة أخرى أو ينقله إليها' },
  { program: 'portage', domain: 'social', text: 'ينصت للموسيقى أو القصص لمدة تتراوح ما بين 5 – 10 دقائق' },
  { program: 'portage', domain: 'social', text: 'يقول (من فضلك) أو (ممكن) و(شكراً) عند تذكيره' },
  { program: 'portage', domain: 'social', text: 'يحاول مساعدة والديه في الأعمال بالمشاركة في جزء منها (الإمساك بجاروف المكنسة)' },
  { program: 'portage', domain: 'social', text: 'يلعب لعبة ارتداء ملابس الكبار' },
  { program: 'portage', domain: 'social', text: 'يقوم بالاختيار عندما يطلب منه ذلك' },
  { program: 'portage', domain: 'social', text: 'يظهر تفهمه للمشاعر بالتعبير اللفظي عن الحب، الغضب، الحزن، السعادة،... إلخ' },
  // 3-4 سنوات
  { program: 'portage', domain: 'social', text: 'يغني ويقص على نغمات الموسيقى' },
  { program: 'portage', domain: 'social', text: 'يتبع القواعد بتقليد أفعال الأطفال الآخرين' },
  { program: 'portage', domain: 'social', text: 'يحيي الكبار المألوفين له دون تذكيره' },
  { program: 'portage', domain: 'social', text: 'يتبع القواعد في الألعاب الجماعية التي يقودها شخص كبير' },
  { program: 'portage', domain: 'social', text: 'يطلب الإذن لاستخدام لعبة يلعب بها أقرانه' },
  { program: 'portage', domain: 'social', text: 'يقول "من فضلك" أو "ممكن" أو شكراً دون تذكيره 50% من الوقت' },
  { program: 'portage', domain: 'social', text: 'يرد على المكالمات التليفونية وينادي على شخص كبير أو يتحدث مع شخص مألوف له' },
  { program: 'portage', domain: 'social', text: 'يأخذ دوره (ينتظر دوره)' },
  { program: 'portage', domain: 'social', text: 'يتبع القواعد في الألعاب الجماعية التي يقودها طفل أكبر منه سناً' },
  { program: 'portage', domain: 'social', text: 'يتعاون مع طلبات الكبار 50% من الوقت' },
  { program: 'portage', domain: 'social', text: 'يبقى في المساحة المخصصة للعب بإشراف شخص كبير خارج البيت' },
  { program: 'portage', domain: 'social', text: 'يلعب بالقرب من أطفال آخرين ويتحدث معهم أثناء قيامه بعمل معين (لمدة 30 دقيقة)' },
  // 4-5 سنوات
  { program: 'portage', domain: 'social', text: 'يطلب المساعدة عندما يواجه صعوبة (في الحمام أو في الحصول على ماء)' },
  { program: 'portage', domain: 'social', text: 'يشارك في حديث الكبار' },
  { program: 'portage', domain: 'social', text: 'يردد الأناشيد أو الأغاني أو يرقص للآخرين' },
  { program: 'portage', domain: 'social', text: 'يعمل منفرداً في مهمة لمدة 20 – 30 دقيقة' },
  { program: 'portage', domain: 'social', text: 'يعتذر بدون تذكيره 50% من الوقت' },
  { program: 'portage', domain: 'social', text: 'يأخذ دوره مع 8 – 9 أطفال آخرين' },
  { program: 'portage', domain: 'social', text: 'يلعب مع طفلين أو ثلاثة لمدة 20 دقيقة في نشاط تعاوني (مشروع أو لعبة)' },
  { program: 'portage', domain: 'social', text: 'يتصرف علنية بطريقة مقبولة اجتماعياً' },
  { program: 'portage', domain: 'social', text: 'يطلب الإذن لاستخدام أشياء تخص الآخرين 75% من الوقت' },
  // 5-6 سنوات
  { program: 'portage', domain: 'social', text: 'يعبر عن مشاعره الخاصة: غضب، سعادة، حب' },
  { program: 'portage', domain: 'social', text: 'يلعب مع 4 – 5 أطفال في نشاط تعاوني دون إشراف دائم' },
  { program: 'portage', domain: 'social', text: 'يشرح قواعد لعبة أو نشاط للآخرين' },
  { program: 'portage', domain: 'social', text: 'يقلد أدوار الكبار' },
  { program: 'portage', domain: 'social', text: 'يشترك في الحوار أثناء لقائه مع الأسرة' },
  { program: 'portage', domain: 'social', text: 'يتبع قواعد لعبة لفظية تتطلب التفكير (مثل "عروستي")' },
  { program: 'portage', domain: 'social', text: 'يواسي زملاء اللعب في وقت الضيق' },
  { program: 'portage', domain: 'social', text: 'يختار أصدقاءه' },
  { program: 'portage', domain: 'social', text: 'يخطط ويبني باستخدام أدوات بسيطة (سطح مائل، عتلة، رافعة، بكرة)' },
  { program: 'portage', domain: 'social', text: 'يحدد أهدافاً لنفسه ويقوم بالنشاط المناسب' },
  { program: 'portage', domain: 'social', text: 'يمثل أجزاء من قصة ما ويؤدي دوراً أو يستعمل العرائس للعب' },

  // ==========================================
  // 3. المجال الحركي (Portage Motor)
  // ==========================================
  // 0-1 سنة
  { program: 'portage', domain: 'motor', text: 'يرمي بذراعيه إلى الأمام عند وضعه على بطنه لمدة 15-25 ثانية' },
  { program: 'portage', domain: 'motor', text: 'يمسح ذراعه أمامه محمولاً على مرفقه' },
  { program: 'portage', domain: 'motor', text: 'يمسح ذراعه ويرفع رأسه 45 درجة' },
  { program: 'portage', domain: 'motor', text: 'يرفع رأسه إلى وضع عمودي' },
  { program: 'portage', domain: 'motor', text: 'يرفع رأسه 90 درجة عند وضعه على بطنه' },
  { program: 'portage', domain: 'motor', text: 'يرفع رأسه وكتفيه وهو مستلقٍ على ظهره، ورأسه وكتفيه مرتفعان' },
  { program: 'portage', domain: 'motor', text: 'يبقى رأسه وكتفيه مرفوعان وهو مستلقٍ على ظهره 50% من الوقت' },
  { program: 'portage', domain: 'motor', text: 'يتحرك ويزحف ويكتشف ما حوله' },
  { program: 'portage', domain: 'motor', text: 'يتقلب من بطنه إلى جنبه ويبقى 50% من الوقت' },
  { program: 'portage', domain: 'motor', text: 'يتدحرج إلى جنبه عند النظر إلى شيء' },
  { program: 'portage', domain: 'motor', text: 'يتحرك بطول جسمه عند الاستلقاء' },
  { program: 'portage', domain: 'motor', text: 'يتدحرج من جنبه إلى بطنه' },
  { program: 'portage', domain: 'motor', text: 'يتقلب من بطنه إلى ظهره' },
  { program: 'portage', domain: 'motor', text: 'يحاول الوصول إلى شيء وهو جالس بمساعدة شخص كبير' },
  { program: 'portage', domain: 'motor', text: 'يدير رأسه بحرية وهو مستلقٍ على بطنه' },
  { program: 'portage', domain: 'motor', text: 'يحافظ على وضع الجلوس لمدة دقيقتين' },
  { program: 'portage', domain: 'motor', text: 'يترك الشيء الذي في يده ليمد يده إلى شيء آخر' },
  { program: 'portage', domain: 'motor', text: 'يقف ويقطع من مكان لآخر' },
  { program: 'portage', domain: 'motor', text: 'يقف منتصباً عند حافة شيء' },
  { program: 'portage', domain: 'motor', text: 'يرفع نفسه إلى وضع الوقوف متمسكاً بشيء أعلى وأثقل' },
  { program: 'portage', domain: 'motor', text: 'يزحف بطول جسمه لكي يصل إلى شيء' },
  { program: 'portage', domain: 'motor', text: 'يجلس وحده مستنداً' },
  { program: 'portage', domain: 'motor', text: 'يتحول من وضع الجلوس إلى وضع الحبو مع انحناء ظهره ورأسه' },
  { program: 'portage', domain: 'motor', text: 'ينتقل إلى وضع الجلوس وهو مستند' },
  { program: 'portage', domain: 'motor', text: 'يجلس دون أن يستند' },
  { program: 'portage', domain: 'motor', text: 'يرمي الأشياء بشكل متعمد' },
  { program: 'portage', domain: 'motor', text: 'يتحرك إلى الخلف والأمام على بطنه' },
  { program: 'portage', domain: 'motor', text: 'ينقل شيئاً من يد إلى أخرى وهو جالس' },
  { program: 'portage', domain: 'motor', text: 'يحافظ على جلوسه مستنداً' },
  { program: 'portage', domain: 'motor', text: 'يحاول وضع نفسه على بطنه' },
  { program: 'portage', domain: 'motor', text: 'يجلس بمفرده' },
  { program: 'portage', domain: 'motor', text: 'يمشي ممسكاً بالأثاث أو على أطراف أصابعه' },
  { program: 'portage', domain: 'motor', text: 'يزحف' },
  { program: 'portage', domain: 'motor', text: 'يمد يده وهو في وضع الجلوس' },
  { program: 'portage', domain: 'motor', text: 'يقف منتصباً عند حافة شيء' },
  { program: 'portage', domain: 'motor', text: 'يحاول الوصول من حوله' },
  { program: 'portage', domain: 'motor', text: 'يقف وحده لمدة دقيقة' },
  { program: 'portage', domain: 'motor', text: 'يمشي بمساعدة' },
  { program: 'portage', domain: 'motor', text: 'يمشي من زاوية إلى أخرى في وقت واحد' },
  { program: 'portage', domain: 'motor', text: 'يعرف اللعبة أو الكرة' },
  { program: 'portage', domain: 'motor', text: 'يضع أشياء صغيرة في وعاء' },
  { program: 'portage', domain: 'motor', text: 'يخفض نفسه ليجلس بعد أن كان واقفاً' },
  { program: 'portage', domain: 'motor', text: 'يصفق بيديه معاً' },
  { program: 'portage', domain: 'motor', text: 'يمشي بمساحة قليلة' },
  { program: 'portage', domain: 'motor', text: 'يمشي خطوات دون أن يتكئ' },
  // 1-2 سنة
  { program: 'portage', domain: 'motor', text: 'يزحف إلى أعلى الدرج' },
  { program: 'portage', domain: 'motor', text: 'ينتقل من وضع الجلوس إلى الوقوف' },
  { program: 'portage', domain: 'motor', text: 'يتحرك جالساً على لعبة ذات عجلات' },
  { program: 'portage', domain: 'motor', text: 'يتسلق على كرسي كبير ويجلس' },
  { program: 'portage', domain: 'motor', text: 'يركب لعبة ذات عجلات 4 دوائر' },
  { program: 'portage', domain: 'motor', text: 'يضع مكعباً في كوب' },
  { program: 'portage', domain: 'motor', text: 'يبني برجاً من 3 مكعبات' },
  { program: 'portage', domain: 'motor', text: 'يرسم علامات بقلم أو قلم تلوين' },
  { program: 'portage', domain: 'motor', text: 'يلعب وحده' },
  { program: 'portage', domain: 'motor', text: 'يمشي إلى الأمام والخلف' },
  { program: 'portage', domain: 'motor', text: 'يجلس على كرسي صغير' },
  { program: 'portage', domain: 'motor', text: 'يركع ثم يقف' },
  { program: 'portage', domain: 'motor', text: 'يدفع ويرمي ويلعب بالكرة' },
  { program: 'portage', domain: 'motor', text: 'يستعمل مقعداً أو صندوقاً صغيراً' },
  { program: 'portage', domain: 'motor', text: 'يصعد الدرج بمساعدة' },
  { program: 'portage', domain: 'motor', text: 'ينحني من الوسط ليلتقط الأشياء دون أن يقع' },
  { program: 'portage', domain: 'motor', text: 'يركل الكرة بحركة عشوائية' },
  // 2-3 سنوات
  { program: 'portage', domain: 'motor', text: 'يضع 4 خواتم كبيرة في عمود خلال دقيقتين' },
  { program: 'portage', domain: 'motor', text: 'يدير مقبض الباب' },
  { program: 'portage', domain: 'motor', text: 'يقفز في مكانه بقدميه معاً' },
  { program: 'portage', domain: 'motor', text: 'يلعب بالصلصال' },
  { program: 'portage', domain: 'motor', text: 'يرمي الكرة بحجم كبير' },
  { program: 'portage', domain: 'motor', text: 'يرمي كرة كبيرة إلى شخص كبير على بعد 1،5 متر دون أن يتحرك' },
  { program: 'portage', domain: 'motor', text: 'يبني برجاً من 5-6 مكعبات' },
  { program: 'portage', domain: 'motor', text: 'يقلب صفحات الكتاب صفحة صفحة' },
  { program: 'portage', domain: 'motor', text: 'يفتح ويفلق لعبة صغيرة' },
  { program: 'portage', domain: 'motor', text: 'يطوي ورقة من نصفها بتقليد' },
  { program: 'portage', domain: 'motor', text: 'يركب ويلعب بالدراجة ذات العجلات الثلاث' },
  { program: 'portage', domain: 'motor', text: 'يخرج بنطالاً ذا أزرار' },
  { program: 'portage', domain: 'motor', text: 'يقفز بقدم ثابتة ومنتظمة' },
  { program: 'portage', domain: 'motor', text: 'يركل من شكل دائري' },
  { program: 'portage', domain: 'motor', text: 'يمسك القلم بين الإبهام والسبابة والوسطى' },
  { program: 'portage', domain: 'motor', text: 'يقفز إلى الأمام بخطوات' },
  { program: 'portage', domain: 'motor', text: 'يقص بالقصارة ويصنع شرائح من الورق' },
  // 3-4 سنوات
  { program: 'portage', domain: 'motor', text: 'يركب صورة من جزء لا يقل عن ثلاثة أشكال أو قطع' },
  { program: 'portage', domain: 'motor', text: 'يقص بالمقص' },
  { program: 'portage', domain: 'motor', text: 'يقفز من ارتفاع 20 سم' },
  { program: 'portage', domain: 'motor', text: 'يقفز بقدميه معاً إلى الأمام مسافة كبيرة' },
  { program: 'portage', domain: 'motor', text: 'يلعب على أطراف أصابعه' },
  { program: 'portage', domain: 'motor', text: 'يمشي 10 خطوات بخطوات متساوية ومتناسقة على خط مستقيم' },
  { program: 'portage', domain: 'motor', text: 'يتقدم 1،5 متر على عارضة ارتفاعها 30 سم' },
  { program: 'portage', domain: 'motor', text: 'يتراجع إلى الخلف عندما يدفعه أحد في البداية' },
  { program: 'portage', domain: 'motor', text: 'يمشي ويرتقي على عارضة ارتفاعها 1-2 متر' },
  { program: 'portage', domain: 'motor', text: 'يقفز إلى الأمام بخطوات' },
  { program: 'portage', domain: 'motor', text: 'يصعد وينزل الدرج بالتبادل بين القدمين' },
  { program: 'portage', domain: 'motor', text: 'يلعب كالجندى' },
  { program: 'portage', domain: 'motor', text: 'يرمي كرة كبيرة إليه' },
  { program: 'portage', domain: 'motor', text: 'يتبع حركات الشكل' },
  { program: 'portage', domain: 'motor', text: 'يقص خطاً مستقيماً طوله 12 سم دون أن ينحرف عنه أكثر من 1 سم' },
  // 4-5 سنوات
  { program: 'portage', domain: 'motor', text: 'يقف على قدم واحدة لمدة 4-8 ثوان دون مساعدة' },
  { program: 'portage', domain: 'motor', text: 'يجري بمهارة' },
  { program: 'portage', domain: 'motor', text: 'يلعب على خشبة التوازن' },
  { program: 'portage', domain: 'motor', text: 'يقفز إلى الأمام 10 مرات دون أن يقع' },
  { program: 'portage', domain: 'motor', text: 'يقفز من ارتفاع 5 سم عن الأرض' },
  { program: 'portage', domain: 'motor', text: 'يقفز 6 مرات للقفز' },
  { program: 'portage', domain: 'motor', text: 'يضرب كرة كبيرة على الأرض ثم يلتقطها' },
  { program: 'portage', domain: 'motor', text: 'يشكل طيناً أو عجيناً إلى ثلاث قطع أو شكلين' },
  { program: 'portage', domain: 'motor', text: 'يقص على خط منحني' },
  { program: 'portage', domain: 'motor', text: 'يركب لعبة ذات أزرار' },
  { program: 'portage', domain: 'motor', text: 'يرمي الكرة ويرتقي بالقدمين بالتبادل' },
  { program: 'portage', domain: 'motor', text: 'يركب دراجة ذات 3 عجلات بمهارة' },
  { program: 'portage', domain: 'motor', text: 'يمشي على خط مستقيم بطول 5 خطوات' },
  { program: 'portage', domain: 'motor', text: 'يقف على قدم واحدة 5 مرات متتالية' },
  { program: 'portage', domain: 'motor', text: 'يرسم صورة بسيطة (مثل: بيت - شجرة - رجل)' },
  { program: 'portage', domain: 'motor', text: 'يقص ويلصق أشكالاً بسيطة' },
  // 5-6 سنوات
  { program: 'portage', domain: 'motor', text: 'يكتب حرفاً منفصلاً في أي مكان على الورقة' },
  { program: 'portage', domain: 'motor', text: 'يلعب على خشبة التوازن بالمشي والأطراف والأيدي' },
  { program: 'portage', domain: 'motor', text: 'يرمي الكرة ويرميها' },
  { program: 'portage', domain: 'motor', text: 'يتراجع على حركات رجعية بسيطة ويحافظ عليها' },
  { program: 'portage', domain: 'motor', text: 'يفرق أصابعه ويلعب بها' },
  { program: 'portage', domain: 'motor', text: 'يستعمل ورقة الكتابة' },
  { program: 'portage', domain: 'motor', text: 'يمشي على عارضة ارتفاع 2 متر للتسلق' },
  { program: 'portage', domain: 'motor', text: 'يرمي بالمسطرة على هدف' },
  { program: 'portage', domain: 'motor', text: 'يضرب الكرة بيده نحو هدف معين' },
  { program: 'portage', domain: 'motor', text: 'يمشي داخل الخطوط 95% من الوقت' },
  { program: 'portage', domain: 'motor', text: 'يقص صورة من أكثر من جهة دون أن يبتعد عن الصورة أكثر من 1 سم' },
  { program: 'portage', domain: 'motor', text: 'يستعمل المبراة' },
  { program: 'portage', domain: 'motor', text: 'يرسم أشكالاً معقدة' },
  { program: 'portage', domain: 'motor', text: 'يركب أشكالاً بسيطة من ورقة' },
  { program: 'portage', domain: 'motor', text: 'يثنى قطره 12 سم من ورقة مربعة بقطر 2 سم' },
  { program: 'portage', domain: 'motor', text: 'يمسك بكرة صغيرة أو خرزة بيد واحدة' },
  { program: 'portage', domain: 'motor', text: 'يستطيع أن يطيح طائرة ورقية' },
  { program: 'portage', domain: 'motor', text: 'يضرب الكرة بالمضرب' },
  { program: 'portage', domain: 'motor', text: 'يرمي شيئاً من على الأرض وهو يجري' },
  { program: 'portage', domain: 'motor', text: 'يتزلج مسافة 2 متر' },
  { program: 'portage', domain: 'motor', text: 'يركب دراجة' },
  { program: 'portage', domain: 'motor', text: 'يتسلق على الحبل' },
  { program: 'portage', domain: 'motor', text: 'يمشي أو يسبح على ظهره' },
  { program: 'portage', domain: 'motor', text: 'يرمي كرة صغيرة بيد واحدة' },
  { program: 'portage', domain: 'motor', text: 'يمشي على قدم واحدة ثم يقفز' },
  { program: 'portage', domain: 'motor', text: 'يكتب اسمه على ورقة' },
  { program: 'portage', domain: 'motor', text: 'يقفز من ارتفاع 30 سم على قدميه معاً' },
  { program: 'portage', domain: 'motor', text: 'يقف على قدم واحدة لمدة 10 ثوان دون أن يتحرك' },
  { program: 'portage', domain: 'motor', text: 'يرمي كرة على هدف ويضع جسمه على يده' },

  // ==========================================
  // 4. مجال الرعاية الذاتية (Portage Self-Help)
  // ==========================================
  // 0-1 سنة
  { program: 'portage', domain: 'selfhelp', text: 'يمص ويتناول الطعام من الأوعية' },
  { program: 'portage', domain: 'selfhelp', text: 'يأكل طعاماً ممزوجاً بمفرده مثل السيريال أو البسكويت الممزوج بالحليب' },
  { program: 'portage', domain: 'selfhelp', text: 'يمد يده إلى زجاجة الرضاعة' },
  { program: 'portage', domain: 'selfhelp', text: 'يأكل قطع البسكويت أو الطعام الذي يعطيه له أحد الوالدين' },
  { program: 'portage', domain: 'selfhelp', text: 'يمسك الزجاجة عند الرضاعة دون أي مساعدة' },
  { program: 'portage', domain: 'selfhelp', text: 'يوجه الزجاجة بفمه أو يدفعها بعيداً' },
  { program: 'portage', domain: 'selfhelp', text: 'يأكل طعاماً مهروساً مثل الموز أو الأفوكادو' },
  { program: 'portage', domain: 'selfhelp', text: 'يشرب من كوب بمساعدة أحد الوالدين' },
  { program: 'portage', domain: 'selfhelp', text: 'يأكل خبزاً أو بسكويتاً أو موزاً' },
  { program: 'portage', domain: 'selfhelp', text: 'يطعم نفسه بأصابعه' },
  { program: 'portage', domain: 'selfhelp', text: 'يمسك ويشرب باستخدام يديه كلتاهما' },
  { program: 'portage', domain: 'selfhelp', text: 'يأخذ لقمة بطعامه ويضعها في فمه بمساعدة' },
  // 1-2 سنة
  { program: 'portage', domain: 'selfhelp', text: 'يفرد رجليه عند لبس الحذاء' },
  { program: 'portage', domain: 'selfhelp', text: 'يأكل طعاماً صلباً بمفرده باستخدام الملعقة' },
  { program: 'portage', domain: 'selfhelp', text: 'يمسك ويشرب من كوب بيد واحدة' },
  { program: 'portage', domain: 'selfhelp', text: 'يمسح يديه بالمنشفة ثم يضعهما في الماء' },
  { program: 'portage', domain: 'selfhelp', text: 'يجلس على المقعد الخاص بالأطفال أو الكرسي الصغير لمدة 5 دقائق' },
  { program: 'portage', domain: 'selfhelp', text: 'يضع القبعة على رأسه ويرفعها' },
  { program: 'portage', domain: 'selfhelp', text: 'يخلع الجوارب' },
  { program: 'portage', domain: 'selfhelp', text: 'يدفع رجليه عبر فتحات السروال أو البنطلون' },
  { program: 'portage', domain: 'selfhelp', text: 'يخلع الحذاء غير المقيد أو السائب' },
  { program: 'portage', domain: 'selfhelp', text: 'يخلع معطفه الخاص عند فك الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: 'يخلع البنطلون عند فك الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: 'يفتح أو يغلق السحاب (الزيبر) في بعض الأحيان لكنه لا يربطه' },
  { program: 'portage', domain: 'selfhelp', text: 'يستخدم كلمات أو إشارات للإشارة إلى حاجته للذهاب إلى الحمام' },
  // 2-3 سنوات
  { program: 'portage', domain: 'selfhelp', text: 'يطعم نفسه باستخدام الملعقة والشوكة مع انسكاب قليل' },
  { program: 'portage', domain: 'selfhelp', text: 'يأخذ منشفة من أحد الوالدين ويمسح يديه ووجهه' },
  { program: 'portage', domain: 'selfhelp', text: 'يشرب سائلاً من كوب أو إبريق باستخدام مقبض' },
  { program: 'portage', domain: 'selfhelp', text: 'يعرف الحذاء' },
  { program: 'portage', domain: 'selfhelp', text: 'يمضغ ويبلع الأطعمة المناسبة للطفل فقط' },
  { program: 'portage', domain: 'selfhelp', text: 'ينشف يديه دون مساعدة عند إعطاء المنشفة' },
  { program: 'portage', domain: 'selfhelp', text: 'يطلب الذهاب للحمام حتى لو كان متسخاً' },
  { program: 'portage', domain: 'selfhelp', text: 'يتحكم في عضلات الفم والبلع' },
  { program: 'portage', domain: 'selfhelp', text: 'يتقلب ويلتف في البطانية ثلاث مرات عند وضعه للنوم' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس الحذاء' },
  { program: 'portage', domain: 'selfhelp', text: 'يفرد السروال الداخلي' },
  { program: 'portage', domain: 'selfhelp', text: 'يخلع قميصاً بسيطاً مفتوحاً' },
  { program: 'portage', domain: 'selfhelp', text: 'يستخدم الحمام عند الحاجة، أثناء الاستيقاظ أو بعد القيلولة' },
  { program: 'portage', domain: 'selfhelp', text: 'يصل إلى الماء من الصنبور دون مساعدة عند التوضأ أو غسل يديه' },
  { program: 'portage', domain: 'selfhelp', text: 'ينظم درجة حرارة الماء ويغسل يديه ووجهه عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: 'يطلب الذهاب إلى الحمام عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: 'يضع المعطف على علاقة ملابس بطول الطفل' },
  { program: 'portage', domain: 'selfhelp', text: 'يبقى جافاً خلال القيلولة القصيرة' },
  { program: 'portage', domain: 'selfhelp', text: 'يتجنب الأصوات المفاجئة مثل الأبواب المغلقة أو الصفير' },
  { program: 'portage', domain: 'selfhelp', text: 'يستخدم منشفة الشعر عند التذكير' },
  { program: 'portage', domain: 'selfhelp', text: 'يزرر قميصاً كبيراً أو معطفاً' },
  { program: 'portage', domain: 'selfhelp', text: 'يصيب هدفاً صغيراً في لعبة الرمي دون مساعدة' },
  { program: 'portage', domain: 'selfhelp', text: 'يغطي وجهه بمنشفة' },
  { program: 'portage', domain: 'selfhelp', text: 'يغسل يديه ورجليه بنفسه عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس جواربه' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس قميصه، حذاءه، معطفه الخاص' },
  { program: 'portage', domain: 'selfhelp', text: 'يجد وجه المنشفة' },
  // 3-4 سنوات
  { program: 'portage', domain: 'selfhelp', text: 'يطعم نفسه بالكامل' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس نفسه بمساعدة عند الحاجة أو لارتداء المعطف' },
  { program: 'portage', domain: 'selfhelp', text: 'يمسح أنفه عند التذكير' },
  { program: 'portage', domain: 'selfhelp', text: 'يستيقظ جافاً سبع ليالٍ من أصل ثمانية' },
  { program: 'portage', domain: 'selfhelp', text: 'يتذكر الذهاب للحمام ويخلع ملابسه' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس ويرتدي الجوارب والأحذية والملابس 75% من الوقت' },
  { program: 'portage', domain: 'selfhelp', text: 'يفتح أو يغلق الأزرار الكبيرة' },
  { program: 'portage', domain: 'selfhelp', text: 'ينفخ أنفه عند التذكير' },
  { program: 'portage', domain: 'selfhelp', text: 'يتجنب الأحذية المقلوبة (اليمين واليسار)' },
  { program: 'portage', domain: 'selfhelp', text: 'يعلق المعطف على العلاقة ويضع الحذاء في مكانه' },
  { program: 'portage', domain: 'selfhelp', text: 'يفرش أسنانه عند إعطائه تعليمات لفظية' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس القفازات (بإصبع واحد لكل قفاز)' },
  { program: 'portage', domain: 'selfhelp', text: 'يفتح أزراراً كبيرة على فتحات الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: 'يزرر أزراراً كبيرة على فتحات الأزرار' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس الحذاء ذو الرباط' },
  // 4-5 سنوات
  { program: 'portage', domain: 'selfhelp', text: 'يمسح أنفه عند الحاجة' },
  { program: 'portage', domain: 'selfhelp', text: 'يتجنب المواد الخطرة والملوثة' },
  { program: 'portage', domain: 'selfhelp', text: 'يغطي فمه' },
  { program: 'portage', domain: 'selfhelp', text: 'يزرر قميصه' },
  { program: 'portage', domain: 'selfhelp', text: 'يختار طعامه من الأطعمة التي تناولها' },
  { program: 'portage', domain: 'selfhelp', text: 'يطعم نفسه بالملعقة' },
  { program: 'portage', domain: 'selfhelp', text: 'يغسل يديه ووجهه' },
  { program: 'portage', domain: 'selfhelp', text: 'يستخدم الأدوات الصحيحة للأكل' },
  { program: 'portage', domain: 'selfhelp', text: 'يبقى جافاً طوال الليل أو يستيقظ ويذهب للحمام' },
  { program: 'portage', domain: 'selfhelp', text: 'يمسح أنفه وينفخه 75% من الوقت عند الحاجة دون تذكير' },
  { program: 'portage', domain: 'selfhelp', text: 'يغسل نفسه جيداً (اليدين، الوجه، الأذنين)' },
  { program: 'portage', domain: 'selfhelp', text: 'يستخدم السكين لدهان قطعة من الخبز المحمص بالزبدة أو المربى' },
  { program: 'portage', domain: 'selfhelp', text: 'يربط ويغلق الحذاء أو البنطلون' },
  { program: 'portage', domain: 'selfhelp', text: 'يلبس نفسه بالكامل بما في ذلك ربط الأحذية' },
  { program: 'portage', domain: 'selfhelp', text: 'ينام في سريره بينما يحمل أحد الوالدين البطانية' },
  { program: 'portage', domain: 'selfhelp', text: 'يساعد في إعداد المائدة ووضع الأدوات عند إعطائه تعليمات لفظية' },
  { program: 'portage', domain: 'selfhelp', text: 'يفرش أسنانه' },
  { program: 'portage', domain: 'selfhelp', text: 'يذهب للحمام فيستحم ويغسل نفسه بالشامبو ويجفف نفسه ويرتدي ملابسه دون مساعدة' },
  { program: 'portage', domain: 'selfhelp', text: 'يمشط شعره الطويل باستخدام المشط أو الفرشاة' },
  { program: 'portage', domain: 'selfhelp', text: 'يعلق المنشفة على العلاقة' },
  { program: 'portage', domain: 'selfhelp', text: 'يتصرف بحذر دون مراقبة' },
  { program: 'portage', domain: 'selfhelp', text: 'يربط حذاءه بإدخال الرباط في الفتحات' },
  { program: 'portage', domain: 'selfhelp', text: 'يربط حذاءه (عقدة)' },
  // 5-6 سنوات
  { program: 'portage', domain: 'selfhelp', text: 'يتحمل مسؤولية مهمة أسبوعية في المنزل عند طلب ذلك' },
  { program: 'portage', domain: 'selfhelp', text: 'يختار ملابس مناسبة لدرجة الحرارة المناسبة' },
  { program: 'portage', domain: 'selfhelp', text: 'يقف عند المنحدر ثم ينظر للجانبين ثم يعبر الشارع دون تذكيرات لفظية' },
  { program: 'portage', domain: 'selfhelp', text: 'يضع الطعام في طبق ثم يمرر الطبق للآخرين ثم يغطي الطعام' },
  { program: 'portage', domain: 'selfhelp', text: 'يحضر وجبته الخاصة من الحقيبة ويضع الزبدة أو المربى' },
  { program: 'portage', domain: 'selfhelp', text: 'يتحمل مسؤولية مهمة يومية في المنزل (إعداد المائدة، تحضير الطعام)' },
  { program: 'portage', domain: 'selfhelp', text: 'ينظم درجة حرارة الماء عند أخذ حمام ساخن أو بارد' },
  { program: 'portage', domain: 'selfhelp', text: 'يحضر نفسه للنوم' },
  { program: 'portage', domain: 'selfhelp', text: 'يذهب إلى المدرسة أو الملعب أو الحديقة بمفرده من المنزل' },
  { program: 'portage', domain: 'selfhelp', text: 'يقطع طعامه بالسكين (بطاطس مقلية، تفاح، خبز)' },
  { program: 'portage', domain: 'selfhelp', text: 'يجد الحمام العام في المكان العام' },
  { program: 'portage', domain: 'selfhelp', text: 'يفتح علبة لبن مصنوعة من الكرتون' },
  { program: 'portage', domain: 'selfhelp', text: 'يرمي الكرة في سلة المهملات' },
  { program: 'portage', domain: 'selfhelp', text: 'يربط حبل الهاتف أو الكهرباء' },
  { program: 'portage', domain: 'selfhelp', text: 'يربط حزام الأمان في السيارة' },

  // ==========================================
  // 5. المجال المعرفي (Portage Cognitive)
  // ==========================================
  // 0-1 سنة
  { program: 'portage', domain: 'cognitive', text: 'يلتقط قطعة من الطعام (أو الفطيرة) ويضعها في فمه' },
  { program: 'portage', domain: 'cognitive', text: 'يبحث عن شيء رفعت من خط رؤيته المباشر' },
  { program: 'portage', domain: 'cognitive', text: 'يرفع شيئاً من وعاء مفتوح وذلك بوضع يده فيه' },
  { program: 'portage', domain: 'cognitive', text: 'يضع أشياء في وعاء بمقاس كبير' },
  { program: 'portage', domain: 'cognitive', text: 'يضع الأشياء في الوعاء عند الطلب اللفظي' },
  { program: 'portage', domain: 'cognitive', text: 'يضغط بيده على صندوق ليعطي صوتاً' },
  { program: 'portage', domain: 'cognitive', text: 'يضع ثلاث أدوات في وعاء' },
  { program: 'portage', domain: 'cognitive', text: 'ينقل أداة من يد إلى أخرى لالتقاط أداة أخرى' },
  { program: 'portage', domain: 'cognitive', text: 'يسقط ويضغط على الأشياء' },
  { program: 'portage', domain: 'cognitive', text: 'يجد أداة مخفية تحت بطانية' },
  { program: 'portage', domain: 'cognitive', text: 'يدفع ثلاث مكعبات عبر خط مستقيم' },
  { program: 'portage', domain: 'cognitive', text: 'يرفع يديه عن الأشكال الهندسية' },
  { program: 'portage', domain: 'cognitive', text: 'يضع خواتم على عمود دائري عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يقوم بحركات بسيطة عند الطلب' },
  // 1-2 سنة
  { program: 'portage', domain: 'cognitive', text: 'يفرز 6 أدوات من وعاء' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى جزء واحد من جسمه' },
  { program: 'portage', domain: 'cognitive', text: 'يركب 3 مكعبات فوق بعضها عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق أدوات متشابهة' },
  { program: 'portage', domain: 'cognitive', text: 'يفرز (الأشياء)' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى نفسه عند السؤال "أين أنت؟" أو عند ذكر اسمه' },
  { program: 'portage', domain: 'cognitive', text: 'يضع 5 خواتم دائرية في عمود عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق أدوات مع صور الأشياء' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى صورة الحيوان' },
  { program: 'portage', domain: 'cognitive', text: 'يقلب من 2-3 صفحات من كتاب الصور في المرة الواحدة' },
  // 2-3 سنوات
  { program: 'portage', domain: 'cognitive', text: 'يجد كتاباً معيناً عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يكمل 3 أشكال في لوحة الأشكال' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي 4 صور مألوفة' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم خط عمودياً بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم خط أفقياً بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم دائرة' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق بين الألوان الأساسية' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى كبير وصغير عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم علامة (+) بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق الألوان الأساسية الثلاثة' },
  { program: 'portage', domain: 'cognitive', text: 'يضع الأشياء تحت وفوق وداخل عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي أدوات تصدر أصواتاً' },
  { program: 'portage', domain: 'cognitive', text: 'يضع 4 أجزاء من لعبة تركيبية معاً' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي حركات تمثلها الأشياء' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق الأشكال الهندسية مع صور الأشكال' },
  { program: 'portage', domain: 'cognitive', text: 'يعد أكثر من خمسة أو ستة من المكعبات بالترتيب' },
  // 3-4 سنوات
  { program: 'portage', domain: 'cognitive', text: 'يسمي الأشياء الصغيرة والكبيرة' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى 10 أجزاء من الجسم عند التقليد للتعليمات اللفظية' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى ولد وبنت عند الطلب اللفظي' },
  { program: 'portage', domain: 'cognitive', text: 'يخبر ما إذا كانت الأشياء ثقيلة أو خفيفة' },
  { program: 'portage', domain: 'cognitive', text: 'يضع جزأين من شكل لعمل شكل كامل' },
  { program: 'portage', domain: 'cognitive', text: 'يصف برنامجاً أو أثنين من شخصيتين من قصة أو صورة' },
  { program: 'portage', domain: 'cognitive', text: 'يلعب بدمى ويغني ويركب حركات' },
  { program: 'portage', domain: 'cognitive', text: 'يقارن 1 إلى 13 الأشياء الأكثر أو الأقل' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى الأشياء الطويلة والقصيرة' },
  { program: 'portage', domain: 'cognitive', text: 'يخبر أي الأشياء تتناسب معاً' },
  { program: 'portage', domain: 'cognitive', text: 'يعد إلى ثلاثة بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يرتب الأشياء في فئات' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم شكل V بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم خط قطري من زاوية إلى الزاوية الأخرى لمربع' },
  { program: 'portage', domain: 'cognitive', text: 'يعد إلى 10 أدوات' },
  { program: 'portage', domain: 'cognitive', text: 'يبني جسراً من 3 مكعبات بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق نموذجاً أو تسلسلاً من المكعبات أو الخواتم' },
  { program: 'portage', domain: 'cognitive', text: 'يرسل تسلسلاً متصلاً (مثل vvvvvvv)' },
  { program: 'portage', domain: 'cognitive', text: 'يضيف رجلاً و/أو ذراعاً إلى شكل شخص غير كامل' },
  { program: 'portage', domain: 'cognitive', text: 'يكمل صورة من 6 قطع أو أكثر بدون محاولة أو خطأ' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي الأشياء إما متشابهة أو مختلفة' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم مربعاً بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي 3 ألوان عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي الأشكال الهندسية: مربع، مثلث، دائرة' },
  // 4-5 سنوات
  { program: 'portage', domain: 'cognitive', text: 'يطرق عدداً محدداً من الأدوات 1-5 عند الطلب اللفظي' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي خمسة ألوان' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم المثلث عند الطلب' },
  { program: 'portage', domain: 'cognitive', text: 'يذكر 4 أشياء في الصورة' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي الوقت من الساعة المرتبط بنشاط' },
  { program: 'portage', domain: 'cognitive', text: 'يعيد أصوات الحيوانات المألوفة' },
  { program: 'portage', domain: 'cognitive', text: 'يخبر إذا كان الشيء أقل أو أصغر (نصف كوب أو أقل)' },
  { program: 'portage', domain: 'cognitive', text: 'يخبر بما هو ناقص عندما تختفي أداة من مجموعة مكونة من 3 أدوات' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي 8 ألوان' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي النصف والربع' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق الحروف والأرقام' },
  { program: 'portage', domain: 'cognitive', text: 'يقول لون الأشياء' },
  { program: 'portage', domain: 'cognitive', text: 'يدرس 5 صور من قصة قصيرة 3 مرات' },
  { program: 'portage', domain: 'cognitive', text: 'يرسم رجلاً (الرأس، الأطراف، الجسم)' },
  { program: 'portage', domain: 'cognitive', text: 'يعيد 5 أصوات من سلسلة' },
  { program: 'portage', domain: 'cognitive', text: 'يبني هرماً من 10 مكعبات بالمقلد' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي طويلاً وقصيراً' },
  { program: 'portage', domain: 'cognitive', text: 'يضع أدوات بالترتيب، بالجانب، بالخلف' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق مجموعات متساوية من 1 إلى 10 أشياء' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي أو يشير إلى الجزء الناقص من الصورة' },
  { program: 'portage', domain: 'cognitive', text: 'يعد من الذاكرة من 1 – 20' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي الأول، الأوسط، الأخير إما موضوعاً' },
  // 5-6 سنوات
  { program: 'portage', domain: 'cognitive', text: 'يعد إلى 20 ويقول الرقم والشيء' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي 10 أرقام مكتوبة' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي اليمين واليسار على نفسه' },
  { program: 'portage', domain: 'cognitive', text: 'يقول الحروف الأبجدية بالترتيب' },
  { program: 'portage', domain: 'cognitive', text: 'يكتب اسمه الأول' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي 5 حروف كبيرة' },
  { program: 'portage', domain: 'cognitive', text: 'يرتب الأشياء للطول والعرض' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي الحروف الأبجدية بالترتيب' },
  { program: 'portage', domain: 'cognitive', text: 'يضع الأرقام المكتوبة من 1 إلى 10 في الترتيب الصحيح' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي وضع الأشياء إما الأول، الثاني، الثالث' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي الحروف مفردة أو متصلة' },
  { program: 'portage', domain: 'cognitive', text: 'يطابق الحرف في بداية الكلمة والكلمة' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى الأرقام المكتوبة من 1 - 25' },
  { program: 'portage', domain: 'cognitive', text: 'ينسخ الشكل المحدد' },
  { program: 'portage', domain: 'cognitive', text: 'يكمل متاهات بسيطة' },
  { program: 'portage', domain: 'cognitive', text: 'يسمي أيام الأسبوع بالترتيب' },
  { program: 'portage', domain: 'cognitive', text: 'يستطيع أن يجمع ويوصل إلى ثلاثة مجاميع' },
  { program: 'portage', domain: 'cognitive', text: 'يقول يوماً وأسبوعاً' },
  { program: 'portage', domain: 'cognitive', text: 'يقرأ 10 كلمات بدون توجيه' },
  { program: 'portage', domain: 'cognitive', text: 'يخبر عن شيء سيساعد في موقف ما' },
  { program: 'portage', domain: 'cognitive', text: 'يشير إلى النصف والربع للأشياء' },
  { program: 'portage', domain: 'cognitive', text: 'يعد من الذاكرة' },

  // ==========================================
  // 6. المجال اللغوي (Portage Language)
  // ==========================================
  // 0-1 سنة
  { program: 'portage', domain: 'language', text: 'يسمع الأصوات الصادرة من الآخرين' },
  { program: 'portage', domain: 'language', text: 'يكرر نفس المقطع الصوتي مرتين أو ثلاث مثل (ما ما ما، با با با)' },
  { program: 'portage', domain: 'language', text: 'يستجيب للإشارات بالإشارة' },
  { program: 'portage', domain: 'language', text: 'ينفذ بعض التعليمات البسيطة المصحوبة بالإشارة' },
  { program: 'portage', domain: 'language', text: 'يتوقف عن النشاط 75% من الوقت عندما يقال له "لأ"' },
  { program: 'portage', domain: 'language', text: 'يجيب على أسئلة بسيطة بإجابة غير لفظية' },
  { program: 'portage', domain: 'language', text: 'يربط مقطعين مختلفين من خلال نداء الشخص' },
  { program: 'portage', domain: 'language', text: 'يقلد أغاني الآخرين' },
  { program: 'portage', domain: 'language', text: 'يستخدم كلمة واحدة بمعنى تسمية شخص أو شيء' },
  { program: 'portage', domain: 'language', text: 'يتحدث استجابة لكلام الشخص الآخر' },
  // 1-2 سنة
  { program: 'portage', domain: 'language', text: 'يقول 5 كلمات مختلفة (يمكن استخدام نفس الكلمة لرموز أشياء مختلفة)' },
  { program: 'portage', domain: 'language', text: 'يسأل عن "المزيد"' },
  { program: 'portage', domain: 'language', text: 'يقول "انتهى"' },
  { program: 'portage', domain: 'language', text: 'ينفذ تعليمات مختلفة بخطوة واحدة دون استخدام الإشارة' },
  { program: 'portage', domain: 'language', text: 'يعطي أو يروي عند الطلب منه ذلك' },
  { program: 'portage', domain: 'language', text: 'يشير إلى 12 شيء مألوف لديه عند ذكرها' },
  { program: 'portage', domain: 'language', text: 'يشير إلى 3-5 أجزاء في صورة عند ذكرها' },
  { program: 'portage', domain: 'language', text: 'يشير إلى 3 أجزاء من جسمه' },
  { program: 'portage', domain: 'language', text: 'يقول اسمه الأول أو لقبه عند الطلب منه ذلك' },
  { program: 'portage', domain: 'language', text: 'يجيب على سؤال "ما هذا؟" بإعطاء اسم الشيء' },
  { program: 'portage', domain: 'language', text: 'يربط الكلمات والإشارات للتعبير عن رغباته المعروفة' },
  { program: 'portage', domain: 'language', text: 'يسمي 5 من الحيوانات الموجودة في البيئة المحلية' },
  { program: 'portage', domain: 'language', text: 'يسمي 4 أعضاء اللعبة (العائلة)' },
  { program: 'portage', domain: 'language', text: 'يستخدم أصوات الحيوانات مثل الحيوانات المعروفة كالبقرة والكلب' },
  { program: 'portage', domain: 'language', text: 'يسأل عن بعض أجزاء طعامه المألوف عندما يرى مثل لبن معلب أو بسكويت' },
  { program: 'portage', domain: 'language', text: 'يقول كلمة أو جملة بذلك وبسؤال صغير كذلك' },
  { program: 'portage', domain: 'language', text: 'يسمي 3 أجزاء من جسمه أو جسم شخص آخر' },
  { program: 'portage', domain: 'language', text: 'يجيب على أسئلة "نعم" أو "لا" بإجابة مثبتة أو منفية' },
  // 2-3 سنوات
  { program: 'portage', domain: 'language', text: 'يربط الاسم والصفة أو الاسم والاسم في مقطع من كلمتين (كبير-سيارة)' },
  { program: 'portage', domain: 'language', text: 'يربط الفعل والاسم في مقطع من كلمتين (باب باب)' },
  { program: 'portage', domain: 'language', text: 'يستخدم الكلمة التي تعني الحاجة إلى الذهاب إلى الحمام' },
  { program: 'portage', domain: 'language', text: 'يربط الاسم أو الفعل مع "هنا" و"هناك" مثل جملة قصيرة من كلمتين "هذا كرسي"' },
  { program: 'portage', domain: 'language', text: 'يربط كلمتين للتعبير عن الملكية مثل "سيارة بابا"' },
  { program: 'portage', domain: 'language', text: 'يستخدم "لا" في الأسئلة' },
  { program: 'portage', domain: 'language', text: 'يجيب على سؤال "ماذا تفعل؟" عبر أفعاله العادية' },
  { program: 'portage', domain: 'language', text: 'يجيب على أسئلة "أين" مثل "أين أمك؟"' },
  { program: 'portage', domain: 'language', text: 'يسمي الأصوات المألوفة من البيئة مثل أصوات السيارات' },
  { program: 'portage', domain: 'language', text: 'يعطي أكثر من شيء عند السؤال باستخدام صيغة الجمع مثل "أعطني المكعبات"' },
  { program: 'portage', domain: 'language', text: 'يشير إلى نفسه باستخدام الضمائر' },
  { program: 'portage', domain: 'language', text: 'يشير إلى الصور المألوفة المعروفة (10 صور)' },
  { program: 'portage', domain: 'language', text: 'يرفع صوت عالياً لعمره' },
  { program: 'portage', domain: 'language', text: 'يخبر عن الجنس عند السؤال "أنت ولد أم بنت؟"' },
  { program: 'portage', domain: 'language', text: 'ينفذ 3 أوامر متتالية (يأخذ الطفل الكرسي ويضعه هنا)' },
  { program: 'portage', domain: 'language', text: 'يستخدم الفعل المضارع بشكل صحيح' },
  { program: 'portage', domain: 'language', text: 'يستخدم صيغة الجمع' },
  { program: 'portage', domain: 'language', text: 'يستخدم بعض الأفعال الماضية مثل أكل، لعب' },
  { program: 'portage', domain: 'language', text: 'يسأل أسئلة "ما هذا؟"' },
  { program: 'portage', domain: 'language', text: 'يتحكم في ارتفاع الصوت 90% من الوقت' },
  { program: 'portage', domain: 'language', text: 'يستخدم "هذه" و"تلك" في الحديث' },
  { program: 'portage', domain: 'language', text: 'يستخدم كلمة "هذه" في جملة مثل "هذه كلمة"' },
  // 3-4 سنوات
  { program: 'portage', domain: 'language', text: 'يقول "أنا بدل أنا"' },
  { program: 'portage', domain: 'language', text: 'يشير إلى أشياء ليست موجودة' },
  { program: 'portage', domain: 'language', text: 'يجيب على أسئلة بأسماء مثل "ما اسمك؟"' },
  { program: 'portage', domain: 'language', text: 'يستخدم صيغة الملكية من الاسم مثل "بابا"' },
  { program: 'portage', domain: 'language', text: 'يستخدم "لن" أو "لن" في التعريف أو النفي في الحديث مثل "لن أذهب"' },
  { program: 'portage', domain: 'language', text: 'يستخدم بعض الأسماء لأجزاء من الجسم مثل "الطعام - الحيوانات - اللعب"' },
  { program: 'portage', domain: 'language', text: 'يقول "أستطيع" أو "سأفعل" قبل الفعل أو بعده مثل "أستطيع اللعب"' },
  { program: 'portage', domain: 'language', text: 'يصف الأشياء مفتوحة أو مغلقة' },
  // 4-5 سنوات
  { program: 'portage', domain: 'language', text: 'يقول "هل" في أول السؤال عندما يكون مناسباً' },
  { program: 'portage', domain: 'language', text: 'يجلس مستمعاً 5 دقائق عندما تقرأ له قصة' },
  { program: 'portage', domain: 'language', text: 'ينفذ سلسلة من 3 أوامر غير متتابعة' },
  { program: 'portage', domain: 'language', text: 'يقول الاسم الكامل عند الطلب منه ذلك' },
  { program: 'portage', domain: 'language', text: 'يجيب على أسئلة بسيطة تبدأ بـ "كيف" (كيف تصل إلى القبلة)' },
  { program: 'portage', domain: 'language', text: 'يستخدم صيغة الفعل الماضي' },
  { program: 'portage', domain: 'language', text: 'يخبر عن تجربة مؤلمة' },
  { program: 'portage', domain: 'language', text: 'يخبر عن كيفية استخدام الأشياء المعروفة' },
  { program: 'portage', domain: 'language', text: 'يعبر عن هذا الشيء المقبول باستخدام الضمائر (هذا - أريد - سأذهب)' },
  { program: 'portage', domain: 'language', text: 'يعيد ترتيب الكلمات بطريقة مناسبة للسؤال (هل هو؟ - هل هي؟)' },
  { program: 'portage', domain: 'language', text: 'يستخدم بعض صيغ الجمع الشائعة مثل (أقدام - ألعاب)' },
  { program: 'portage', domain: 'language', text: 'يخبر عن حدثين بالترتيب نفسه الذي حدثا فيه' },
  { program: 'portage', domain: 'language', text: 'ينفذ 3 تعليمات' },
  { program: 'portage', domain: 'language', text: 'يظهر فهم الجملة المركبة (الولد الذي يأكل التفاحة)' },
  { program: 'portage', domain: 'language', text: 'يستطيع أن يجد زوج من الصور/الأشياء عند الطلب' },
  { program: 'portage', domain: 'language', text: 'يستخدم "أستطيع" و"أريد" في الكلام' },
  { program: 'portage', domain: 'language', text: 'يستخدم جملة مرتبطة مثل "ضربت الكرة فارتفعت"' },
  { program: 'portage', domain: 'language', text: 'يستطيع أن يجد أشياء أعلى وأدنى عند الطلب' },
  { program: 'portage', domain: 'language', text: 'يستخدم النفي في "لا - لن - لن أستطيع"' },
  { program: 'portage', domain: 'language', text: 'يستطيع أن يشير إلى الخطوط الصغيرة في الصورة' },
  { program: 'portage', domain: 'language', text: 'يستخدم كلمات "جيد، سيء، قليل، كثير"' },
  { program: 'portage', domain: 'language', text: 'يقول الكلمة الأخيرة في النظر المعكوس' },
  { program: 'portage', domain: 'language', text: 'يخبر قصة قصيرة معروفة دون استخدام صور' },
  { program: 'portage', domain: 'language', text: 'يسمي الصورة التي لا تنتمي إلى فئة معينة' },
  { program: 'portage', domain: 'language', text: 'يخبر أن الكلمتين كانتا على نفس الوزن والاسم (مثل "الحليب والموز")' },
  { program: 'portage', domain: 'language', text: 'يستخدم جملة مركبة مثل (أريد أن آتي لأن...)' },
  { program: 'portage', domain: 'language', text: 'يستطيع أن يخبر إذا كان الصوت عالياً أو منخفضاً' },
  // 5-6 سنوات
  { program: 'portage', domain: 'language', text: 'يستطيع أن يشير إلى كثير، كثير، بعض' },
  { program: 'portage', domain: 'language', text: 'يخبر عن العنوان' },
  { program: 'portage', domain: 'language', text: 'يقول رقم التليفون' },
  { program: 'portage', domain: 'language', text: 'يستطيع أن يشير إلى أكثر، أقل، أقل' },
  { program: 'portage', domain: 'language', text: 'يقول كلمة بسيطة' },
  { program: 'portage', domain: 'language', text: 'يخبر عن التجارب اليومية' },
  { program: 'portage', domain: 'language', text: 'يصف الموقع أو الحركة من حيث البعد والاتجاه والقرب' },
  { program: 'portage', domain: 'language', text: 'يجيب على أسئلة "لماذا" بتفسير' },
  { program: 'portage', domain: 'language', text: 'يضع 3-5 أجزاء متسلسلة من قصة ويرويها' },
  { program: 'portage', domain: 'language', text: 'يضع الكلمات في جمل' },
  { program: 'portage', domain: 'language', text: 'يستطيع أن يقول عكس' },
  { program: 'portage', domain: 'language', text: 'يجيب على أسئلة "ماذا يحدث إذا..."' },
  { program: 'portage', domain: 'language', text: 'يستخدم كلمة "جداً" بمعنى' },
  { program: 'portage', domain: 'language', text: 'يسأل عن معنى كلمات جديدة أو غير مألوفة' },
];
